// src/solid/badge.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/badge";
import { badgeElement, defineBadge, type BadgeSpec, type BadgeElement } from "../elements/badge";
import { createComponent, type MComponent } from "./create";

export const Badge: MComponent<BadgeSpec, BadgeElement> = /*#__PURE__*/ createComponent(badgeElement.spec, defineBadge, "Badge");
