// src/solid/button.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/progress";
import "material/elements/css/button";
import { buttonElement, defineButton, type ButtonSpec, type ButtonElement } from "../elements/button";
import { createComponent, type MComponent } from "./create";

export const Button: MComponent<ButtonSpec, ButtonElement> = /*#__PURE__*/ createComponent(buttonElement.spec, defineButton, "Button");
