// src/solid/card.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/card";
import { cardElement, defineCard, type CardSpec, type CardElement } from "../elements/card";
import { createComponent, type MComponent } from "./create";

export const Card: MComponent<CardSpec, CardElement> = /*#__PURE__*/ createComponent(cardElement.spec, defineCard, "Card");
