// src/solid/carousel-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { carouselItemDeclaration, type CarouselItemAttributes } from "../elements/carousel";
import { createDeclaration, type MDeclaration } from "./create";

export const CarouselItem: MDeclaration<CarouselItemAttributes> = /*#__PURE__*/ createDeclaration(carouselItemDeclaration, "CarouselItem");
