// src/solid/checkbox.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/checkbox";
import { checkboxElement, defineCheckbox, type CheckboxSpec, type CheckboxElement } from "../elements/checkbox";
import { createComponent, type MComponent } from "./create";

export const Checkbox: MComponent<CheckboxSpec, CheckboxElement> = /*#__PURE__*/ createComponent(checkboxElement.spec, defineCheckbox, "Checkbox");
