// src/solid/chips.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/chips";
import { chipsElement, defineChips, type ChipsSpec, type ChipsElement } from "../elements/chips";
import { createComponent, type MComponent } from "./create";

export const Chips: MComponent<ChipsSpec, ChipsElement> = /*#__PURE__*/ createComponent(chipsElement.spec, defineChips, "Chips");
