// src/solid/datepicker.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/datepicker";
import { datepickerElement, defineDatepicker, type DatepickerSpec, type DatepickerElement } from "../elements/datepicker";
import { createComponent, type MComponent } from "./create";

export const Datepicker: MComponent<DatepickerSpec, DatepickerElement> = /*#__PURE__*/ createComponent(datepickerElement.spec, defineDatepicker, "Datepicker");
