// src/solid/fab-menu-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { fabMenuItemDeclaration, type FabMenuItemAttributes } from "../elements/fab-menu";
import { createDeclaration, type MDeclaration } from "./create";

export const FabMenuItem: MDeclaration<FabMenuItemAttributes> = /*#__PURE__*/ createDeclaration(fabMenuItemDeclaration, "FabMenuItem");
