// src/solid/fab-menu.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/fab";
import "mtrl/elements/css/menu";
import "mtrl/elements/css/fab-menu";
import { fabMenuElement, defineFabMenu, type FabMenuSpec, type FabMenuElement } from "../elements/fab-menu";
import { createComponent, type MComponent } from "./create";

export const FabMenu: MComponent<FabMenuSpec, FabMenuElement> = /*#__PURE__*/ createComponent(fabMenuElement.spec, defineFabMenu, "FabMenu");
