// src/solid/icon-button.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/icon-button";
import { iconButtonElement, defineIconButton, type IconButtonSpec, type IconButtonElement } from "../elements/icon-button";
import { createComponent, type MComponent } from "./create";

export const IconButton: MComponent<IconButtonSpec, IconButtonElement> = /*#__PURE__*/ createComponent(iconButtonElement.spec, defineIconButton, "IconButton");
