// src/solid/index.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
/**
 * Solid components for the elements. Each renders its `<m-*>` tag, registers
 * it on mount and loads its CSS.
 *
 * @module solid
 */

import "mtrl/elements/css/progress";
import "mtrl/elements/css/button";
import "mtrl/elements/css/switch";
import "mtrl/elements/css/badge";
import "mtrl/elements/css/tabs";
import "mtrl/elements/css/loading-indicator";
import "mtrl/elements/css/divider";
import "mtrl/elements/css/icon-button";
import "mtrl/elements/css/fab";
import "mtrl/elements/css/extended-fab";
import "mtrl/elements/css/checkbox";
import "mtrl/elements/css/slider";
import "mtrl/elements/css/textfield";
import "mtrl/elements/css/radios";
import "mtrl/elements/css/navigation-rail";
import "mtrl/elements/css/drawer";
import "mtrl/elements/css/top-app-bar";
import "mtrl/elements/css/bottom-app-bar";
import "mtrl/elements/css/button-group";
import "mtrl/elements/css/chips";
import "mtrl/elements/css/list";
import "mtrl/elements/css/card";
import "mtrl/elements/css/carousel";
import "mtrl/elements/css/menu";
import "mtrl/elements/css/select";
import "mtrl/elements/css/split-button";
import "mtrl/elements/css/tooltip";
import "mtrl/elements/css/snackbar";
import {
  buttonElement,
  defineButton,
  switchElement,
  defineSwitch,
  tabsElement,
  defineTabs,
  progressElement,
  defineProgress,
  loadingIndicatorElement,
  defineLoadingIndicator,
  badgeElement,
  defineBadge,
  dividerElement,
  defineDivider,
  iconButtonElement,
  defineIconButton,
  fabElement,
  defineFab,
  extendedFabElement,
  defineExtendedFab,
  checkboxElement,
  defineCheckbox,
  sliderElement,
  defineSlider,
  textfieldElement,
  defineTextfield,
  radiosElement,
  defineRadios,
  navigationRailElement,
  defineNavigationRail,
  drawerElement,
  defineDrawer,
  topAppBarElement,
  defineTopAppBar,
  bottomAppBarElement,
  defineBottomAppBar,
  buttonGroupElement,
  defineButtonGroup,
  chipsElement,
  defineChips,
  listElement,
  defineList,
  cardElement,
  defineCard,
  carouselElement,
  defineCarousel,
  menuElement,
  defineMenu,
  selectElement,
  defineSelect,
  splitButtonElement,
  defineSplitButton,
  tooltipElement,
  defineTooltip,
  snackbarElement,
  defineSnackbar,
  tabDeclaration,
  radioDeclaration,
  navigationRailItemDeclaration,
  drawerItemDeclaration,
  buttonGroupItemDeclaration,
  chipDeclaration,
  listItemDeclaration,
  carouselItemDeclaration,
  menuItemDeclaration,
  selectOptionDeclaration,
} from "../elements";
import type {
  ButtonSpec,
  ButtonElement,
  SwitchSpec,
  SwitchElement,
  TabsSpec,
  TabsElement,
  ProgressSpec,
  ProgressElement,
  LoadingIndicatorSpec,
  LoadingIndicatorElement,
  BadgeSpec,
  BadgeElement,
  DividerSpec,
  DividerElement,
  IconButtonSpec,
  IconButtonElement,
  FabSpec,
  FabElement,
  ExtendedFabSpec,
  ExtendedFabElement,
  CheckboxSpec,
  CheckboxElement,
  SliderSpec,
  SliderElement,
  TextfieldSpec,
  TextfieldElement,
  RadiosSpec,
  RadiosElement,
  NavigationRailSpec,
  NavigationRailElement,
  DrawerSpec,
  DrawerElement,
  TopAppBarSpec,
  TopAppBarElement,
  BottomAppBarSpec,
  BottomAppBarElement,
  ButtonGroupSpec,
  ButtonGroupElement,
  ChipsSpec,
  ChipsElement,
  ListSpec,
  ListElement,
  CardSpec,
  CardElement,
  CarouselSpec,
  CarouselElement,
  MenuSpec,
  MenuElement,
  SelectSpec,
  SelectElement,
  SplitButtonSpec,
  SplitButtonElement,
  TooltipSpec,
  TooltipElement,
  SnackbarSpec,
  SnackbarElement,
  TabAttributes,
  RadioAttributes,
  NavigationRailItemAttributes,
  DrawerItemAttributes,
  ButtonGroupItemAttributes,
  ChipAttributes,
  ListItemAttributes,
  CarouselItemAttributes,
  MenuItemAttributes,
  SelectOptionAttributes,
} from "../elements";
import { createComponent, createDeclaration, type MComponent, type MDeclaration } from "./create";

export { configure } from "./create";
export type { SolidProps, DeclarationProps, EventProps, DefaultProps, FormProps, MComponent, MDeclaration } from "./create";

export const Button: MComponent<ButtonSpec, ButtonElement> = createComponent(buttonElement.spec, defineButton, "Button");
export const Switch: MComponent<SwitchSpec, SwitchElement> = createComponent(switchElement.spec, defineSwitch, "Switch");
export const Tabs: MComponent<TabsSpec, TabsElement> = createComponent(tabsElement.spec, defineTabs, "Tabs");
export const Progress: MComponent<ProgressSpec, ProgressElement> = createComponent(progressElement.spec, defineProgress, "Progress");
export const LoadingIndicator: MComponent<LoadingIndicatorSpec, LoadingIndicatorElement> = createComponent(loadingIndicatorElement.spec, defineLoadingIndicator, "LoadingIndicator");
export const Badge: MComponent<BadgeSpec, BadgeElement> = createComponent(badgeElement.spec, defineBadge, "Badge");
export const Divider: MComponent<DividerSpec, DividerElement> = createComponent(dividerElement.spec, defineDivider, "Divider");
export const IconButton: MComponent<IconButtonSpec, IconButtonElement> = createComponent(iconButtonElement.spec, defineIconButton, "IconButton");
export const Fab: MComponent<FabSpec, FabElement> = createComponent(fabElement.spec, defineFab, "Fab");
export const ExtendedFab: MComponent<ExtendedFabSpec, ExtendedFabElement> = createComponent(extendedFabElement.spec, defineExtendedFab, "ExtendedFab");
export const Checkbox: MComponent<CheckboxSpec, CheckboxElement> = createComponent(checkboxElement.spec, defineCheckbox, "Checkbox");
export const Slider: MComponent<SliderSpec, SliderElement> = createComponent(sliderElement.spec, defineSlider, "Slider");
export const Textfield: MComponent<TextfieldSpec, TextfieldElement> = createComponent(textfieldElement.spec, defineTextfield, "Textfield");
export const Radios: MComponent<RadiosSpec, RadiosElement> = createComponent(radiosElement.spec, defineRadios, "Radios");
export const NavigationRail: MComponent<NavigationRailSpec, NavigationRailElement> = createComponent(navigationRailElement.spec, defineNavigationRail, "NavigationRail");
export const Drawer: MComponent<DrawerSpec, DrawerElement> = createComponent(drawerElement.spec, defineDrawer, "Drawer");
export const TopAppBar: MComponent<TopAppBarSpec, TopAppBarElement> = createComponent(topAppBarElement.spec, defineTopAppBar, "TopAppBar");
export const BottomAppBar: MComponent<BottomAppBarSpec, BottomAppBarElement> = createComponent(bottomAppBarElement.spec, defineBottomAppBar, "BottomAppBar");
export const ButtonGroup: MComponent<ButtonGroupSpec, ButtonGroupElement> = createComponent(buttonGroupElement.spec, defineButtonGroup, "ButtonGroup");
export const Chips: MComponent<ChipsSpec, ChipsElement> = createComponent(chipsElement.spec, defineChips, "Chips");
export const List: MComponent<ListSpec, ListElement> = createComponent(listElement.spec, defineList, "List");
export const Card: MComponent<CardSpec, CardElement> = createComponent(cardElement.spec, defineCard, "Card");
export const Carousel: MComponent<CarouselSpec, CarouselElement> = createComponent(carouselElement.spec, defineCarousel, "Carousel");
export const Menu: MComponent<MenuSpec, MenuElement> = createComponent(menuElement.spec, defineMenu, "Menu");
export const Select: MComponent<SelectSpec, SelectElement> = createComponent(selectElement.spec, defineSelect, "Select");
export const SplitButton: MComponent<SplitButtonSpec, SplitButtonElement> = createComponent(splitButtonElement.spec, defineSplitButton, "SplitButton");
export const Tooltip: MComponent<TooltipSpec, TooltipElement> = createComponent(tooltipElement.spec, defineTooltip, "Tooltip");
export const Snackbar: MComponent<SnackbarSpec, SnackbarElement> = createComponent(snackbarElement.spec, defineSnackbar, "Snackbar");
export const Tab: MDeclaration<TabAttributes> = createDeclaration(tabDeclaration, "Tab");
export const Radio: MDeclaration<RadioAttributes> = createDeclaration(radioDeclaration, "Radio");
export const NavigationRailItem: MDeclaration<NavigationRailItemAttributes> = createDeclaration(navigationRailItemDeclaration, "NavigationRailItem");
export const DrawerItem: MDeclaration<DrawerItemAttributes> = createDeclaration(drawerItemDeclaration, "DrawerItem");
export const ButtonGroupItem: MDeclaration<ButtonGroupItemAttributes> = createDeclaration(buttonGroupItemDeclaration, "ButtonGroupItem");
export const Chip: MDeclaration<ChipAttributes> = createDeclaration(chipDeclaration, "Chip");
export const ListItem: MDeclaration<ListItemAttributes> = createDeclaration(listItemDeclaration, "ListItem");
export const CarouselItem: MDeclaration<CarouselItemAttributes> = createDeclaration(carouselItemDeclaration, "CarouselItem");
export const MenuItem: MDeclaration<MenuItemAttributes> = createDeclaration(menuItemDeclaration, "MenuItem");
export const SelectOption: MDeclaration<SelectOptionAttributes> = createDeclaration(selectOptionDeclaration, "SelectOption");
