// src/solid/index.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
/**
 * Solid components for the elements. Each renders its `<m-*>` tag, registers
 * it on mount and loads its CSS.
 *
 * @module solid
 */

import "mtrl/elements/css/progress";
import "mtrl/elements/css/button";
import "mtrl/elements/css/switch";
import "mtrl/elements/css/badge";
import "mtrl/elements/css/tabs";
import {
  buttonElement,
  defineButton,
  switchElement,
  defineSwitch,
  tabsElement,
  defineTabs,
  tabDeclaration,
} from "../elements";
import type {
  ButtonSpec,
  ButtonElement,
  SwitchSpec,
  SwitchElement,
  TabsSpec,
  TabsElement,
  TabAttributes,
} from "../elements";
import { createComponent, createDeclaration, type MComponent, type MDeclaration } from "./create";

export { configure } from "./create";
export type { SolidProps, DeclarationProps, EventProps, DefaultProps, FormProps, MComponent, MDeclaration } from "./create";

export const Button: MComponent<ButtonSpec, ButtonElement> = createComponent(buttonElement.spec, defineButton, "Button");
export const Switch: MComponent<SwitchSpec, SwitchElement> = createComponent(switchElement.spec, defineSwitch, "Switch");
export const Tabs: MComponent<TabsSpec, TabsElement> = createComponent(tabsElement.spec, defineTabs, "Tabs");
export const Tab: MDeclaration<TabAttributes> = createDeclaration(tabDeclaration, "Tab");
