// src/solid/jsx.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
/**
 * Types the bare `m-*` tags in Solid's JSX, for the elements used directly
 * rather than through the components. Types only, opt in once: `import type {} from "mtrl/solid/jsx";`
 *
 * @module solid/jsx
 */
import type { ElementEvents, ElementMarkup, ElementProperties } from "../elements";
import type { SolidHostAttributes } from "./create";

/** A tag's props: its attributes as markup writes them, and any HTML attribute. */
type Tag<S, E extends HTMLElement> = Omit<SolidHostAttributes<E>, keyof ElementMarkup<S>> & ElementMarkup<S>;

declare module "solid-js" {
  // eslint-disable-next-line @typescript-eslint/no-namespace -- JSX is a namespace; this merges into it
  namespace JSX {
    interface IntrinsicElements {
      "m-button": Tag<import("../elements/button").ButtonSpec, import("../elements/button").ButtonElement>;
      "m-switch": Tag<import("../elements/switch").SwitchSpec, import("../elements/switch").SwitchElement>;
      "m-tabs": Tag<import("../elements/tabs").TabsSpec, import("../elements/tabs").TabsElement>;
      "m-progress": Tag<import("../elements/progress").ProgressSpec, import("../elements/progress").ProgressElement>;
      "m-loading-indicator": Tag<import("../elements/loading-indicator").LoadingIndicatorSpec, import("../elements/loading-indicator").LoadingIndicatorElement>;
      "m-badge": Tag<import("../elements/badge").BadgeSpec, import("../elements/badge").BadgeElement>;
      "m-divider": Tag<import("../elements/divider").DividerSpec, import("../elements/divider").DividerElement>;
      "m-icon-button": Tag<import("../elements/icon-button").IconButtonSpec, import("../elements/icon-button").IconButtonElement>;
      "m-fab": Tag<import("../elements/fab").FabSpec, import("../elements/fab").FabElement>;
      "m-extended-fab": Tag<import("../elements/extended-fab").ExtendedFabSpec, import("../elements/extended-fab").ExtendedFabElement>;
      "m-checkbox": Tag<import("../elements/checkbox").CheckboxSpec, import("../elements/checkbox").CheckboxElement>;
      "m-slider": Tag<import("../elements/slider").SliderSpec, import("../elements/slider").SliderElement>;
      "m-textfield": Tag<import("../elements/textfield").TextfieldSpec, import("../elements/textfield").TextfieldElement>;
      "m-radios": Tag<import("../elements/radios").RadiosSpec, import("../elements/radios").RadiosElement>;
      "m-navigation-bar": Tag<import("../elements/navigation-bar").NavigationBarSpec, import("../elements/navigation-bar").NavigationBarElement>;
      "m-navigation-rail": Tag<import("../elements/navigation-rail").NavigationRailSpec, import("../elements/navigation-rail").NavigationRailElement>;
      "m-drawer": Tag<import("../elements/drawer").DrawerSpec, import("../elements/drawer").DrawerElement>;
      "m-top-app-bar": Tag<import("../elements/top-app-bar").TopAppBarSpec, import("../elements/top-app-bar").TopAppBarElement>;
      "m-bottom-app-bar": Tag<import("../elements/bottom-app-bar").BottomAppBarSpec, import("../elements/bottom-app-bar").BottomAppBarElement>;
      "m-button-group": Tag<import("../elements/button-group").ButtonGroupSpec, import("../elements/button-group").ButtonGroupElement>;
      "m-chips": Tag<import("../elements/chips").ChipsSpec, import("../elements/chips").ChipsElement>;
      "m-list": Tag<import("../elements/list").ListSpec, import("../elements/list").ListElement>;
      "m-card": Tag<import("../elements/card").CardSpec, import("../elements/card").CardElement>;
      "m-carousel": Tag<import("../elements/carousel").CarouselSpec, import("../elements/carousel").CarouselElement>;
      "m-menu": Tag<import("../elements/menu").MenuSpec, import("../elements/menu").MenuElement>;
      "m-fab-menu": Tag<import("../elements/fab-menu").FabMenuSpec, import("../elements/fab-menu").FabMenuElement>;
      "m-select": Tag<import("../elements/select").SelectSpec, import("../elements/select").SelectElement>;
      "m-split-button": Tag<import("../elements/split-button").SplitButtonSpec, import("../elements/split-button").SplitButtonElement>;
      "m-tooltip": Tag<import("../elements/tooltip").TooltipSpec, import("../elements/tooltip").TooltipElement>;
      "m-toolbar": Tag<import("../elements/toolbar").ToolbarSpec, import("../elements/toolbar").ToolbarElement>;
      "m-snackbar": Tag<import("../elements/snackbar").SnackbarSpec, import("../elements/snackbar").SnackbarElement>;
      "m-dialog": Tag<import("../elements/dialog").DialogSpec, import("../elements/dialog").DialogElement>;
      "m-bottom-sheet": Tag<import("../elements/bottom-sheet").BottomSheetSpec, import("../elements/bottom-sheet").BottomSheetElement>;
      "m-side-sheet": Tag<import("../elements/side-sheet").SideSheetSpec, import("../elements/side-sheet").SideSheetElement>;
      "m-datepicker": Tag<import("../elements/datepicker").DatepickerSpec, import("../elements/datepicker").DatepickerElement>;
      "m-timepicker": Tag<import("../elements/timepicker").TimepickerSpec, import("../elements/timepicker").TimepickerElement>;
      "m-search": Tag<import("../elements/search").SearchSpec, import("../elements/search").SearchElement>;
      "m-tab": Tag<typeof import("../elements/tabs").tabDeclaration, HTMLElement>;
      "m-radio": Tag<typeof import("../elements/radios").radioDeclaration, HTMLElement>;
      "m-navigation-bar-item": Tag<typeof import("../elements/navigation-bar").navigationBarItemDeclaration, HTMLElement>;
      "m-navigation-rail-item": Tag<typeof import("../elements/navigation-rail").navigationRailItemDeclaration, HTMLElement>;
      "m-drawer-item": Tag<typeof import("../elements/drawer").drawerItemDeclaration, HTMLElement>;
      "m-button-group-item": Tag<typeof import("../elements/button-group").buttonGroupItemDeclaration, HTMLElement>;
      "m-chip": Tag<typeof import("../elements/chips").chipDeclaration, HTMLElement>;
      "m-list-item": Tag<typeof import("../elements/list").listItemDeclaration, HTMLElement>;
      "m-carousel-item": Tag<typeof import("../elements/carousel").carouselItemDeclaration, HTMLElement>;
      "m-menu-item": Tag<typeof import("../elements/menu").menuItemDeclaration, HTMLElement>;
      "m-fab-menu-item": Tag<typeof import("../elements/fab-menu").fabMenuItemDeclaration, HTMLElement>;
      "m-select-option": Tag<typeof import("../elements/select").selectOptionDeclaration, HTMLElement>;
      "m-search-suggestion": Tag<typeof import("../elements/search").searchSuggestionDeclaration, HTMLElement>;
    }
    /** `prop:checked`, `prop:value`: the elements' live properties. */
    interface ExplicitProperties {
      "checked": NonNullable<ElementProperties<import("../elements/switch").SwitchSpec>["checked"]> | NonNullable<ElementProperties<import("../elements/checkbox").CheckboxSpec>["checked"]>;
      "value": NonNullable<ElementProperties<import("../elements/tabs").TabsSpec>["value"]> | NonNullable<ElementProperties<import("../elements/progress").ProgressSpec>["value"]> | NonNullable<ElementProperties<import("../elements/slider").SliderSpec>["value"]> | NonNullable<ElementProperties<import("../elements/textfield").TextfieldSpec>["value"]> | NonNullable<ElementProperties<import("../elements/radios").RadiosSpec>["value"]> | NonNullable<ElementProperties<import("../elements/navigation-bar").NavigationBarSpec>["value"]> | NonNullable<ElementProperties<import("../elements/navigation-rail").NavigationRailSpec>["value"]> | NonNullable<ElementProperties<import("../elements/drawer").DrawerSpec>["value"]> | NonNullable<ElementProperties<import("../elements/button-group").ButtonGroupSpec>["value"]> | NonNullable<ElementProperties<import("../elements/chips").ChipsSpec>["value"]> | NonNullable<ElementProperties<import("../elements/list").ListSpec>["value"]> | NonNullable<ElementProperties<import("../elements/select").SelectSpec>["value"]> | NonNullable<ElementProperties<import("../elements/datepicker").DatepickerSpec>["value"]> | NonNullable<ElementProperties<import("../elements/timepicker").TimepickerSpec>["value"]> | NonNullable<ElementProperties<import("../elements/search").SearchSpec>["value"]>;
      "indeterminate": NonNullable<ElementProperties<import("../elements/progress").ProgressSpec>["indeterminate"]> | NonNullable<ElementProperties<import("../elements/checkbox").CheckboxSpec>["indeterminate"]>;
      "visible": NonNullable<ElementProperties<import("../elements/badge").BadgeSpec>["visible"]>;
      "selected": NonNullable<ElementProperties<import("../elements/icon-button").IconButtonSpec>["selected"]>;
      "secondValue": NonNullable<ElementProperties<import("../elements/slider").SliderSpec>["secondValue"]>;
      "values": NonNullable<ElementProperties<import("../elements/list").ListSpec>["values"]>;
      "index": NonNullable<ElementProperties<import("../elements/carousel").CarouselSpec>["index"]>;
      "anchor": NonNullable<ElementProperties<import("../elements/menu").MenuSpec>["anchor"]>;
      "target": NonNullable<ElementProperties<import("../elements/tooltip").TooltipSpec>["target"]>;
      "open": NonNullable<ElementProperties<import("../elements/snackbar").SnackbarSpec>["open"]>;
    }
    /** `on:change` and the other element events. */
    interface CustomEvents {
      "change": ElementEvents<import("../elements/button").ButtonSpec>["change"] | ElementEvents<import("../elements/switch").SwitchSpec>["change"] | ElementEvents<import("../elements/tabs").TabsSpec>["change"] | ElementEvents<import("../elements/icon-button").IconButtonSpec>["change"] | ElementEvents<import("../elements/checkbox").CheckboxSpec>["change"] | ElementEvents<import("../elements/slider").SliderSpec>["change"] | ElementEvents<import("../elements/textfield").TextfieldSpec>["change"] | ElementEvents<import("../elements/radios").RadiosSpec>["change"] | ElementEvents<import("../elements/navigation-bar").NavigationBarSpec>["change"] | ElementEvents<import("../elements/navigation-rail").NavigationRailSpec>["change"] | ElementEvents<import("../elements/drawer").DrawerSpec>["change"] | ElementEvents<import("../elements/button-group").ButtonGroupSpec>["change"] | ElementEvents<import("../elements/chips").ChipsSpec>["change"] | ElementEvents<import("../elements/list").ListSpec>["change"] | ElementEvents<import("../elements/carousel").CarouselSpec>["change"] | ElementEvents<import("../elements/select").SelectSpec>["change"] | ElementEvents<import("../elements/datepicker").DatepickerSpec>["change"] | ElementEvents<import("../elements/timepicker").TimepickerSpec>["change"] | ElementEvents<import("../elements/search").SearchSpec>["change"];
      "toggle": ElementEvents<import("../elements/icon-button").IconButtonSpec>["toggle"];
      "collapse": ElementEvents<import("../elements/extended-fab").ExtendedFabSpec>["collapse"] | ElementEvents<import("../elements/navigation-rail").NavigationRailSpec>["collapse"] | ElementEvents<import("../elements/bottom-sheet").BottomSheetSpec>["collapse"];
      "expand": ElementEvents<import("../elements/extended-fab").ExtendedFabSpec>["expand"] | ElementEvents<import("../elements/navigation-rail").NavigationRailSpec>["expand"] | ElementEvents<import("../elements/bottom-sheet").BottomSheetSpec>["expand"];
      "input": ElementEvents<import("../elements/slider").SliderSpec>["input"] | ElementEvents<import("../elements/textfield").TextfieldSpec>["input"] | ElementEvents<import("../elements/timepicker").TimepickerSpec>["input"] | ElementEvents<import("../elements/search").SearchSpec>["input"];
      "visibility": ElementEvents<import("../elements/navigation-bar").NavigationBarSpec>["visibility"];
      "open": ElementEvents<import("../elements/drawer").DrawerSpec>["open"] | ElementEvents<import("../elements/menu").MenuSpec>["open"] | ElementEvents<import("../elements/fab-menu").FabMenuSpec>["open"] | ElementEvents<import("../elements/snackbar").SnackbarSpec>["open"] | ElementEvents<import("../elements/dialog").DialogSpec>["open"] | ElementEvents<import("../elements/bottom-sheet").BottomSheetSpec>["open"] | ElementEvents<import("../elements/side-sheet").SideSheetSpec>["open"] | ElementEvents<import("../elements/datepicker").DatepickerSpec>["open"] | ElementEvents<import("../elements/timepicker").TimepickerSpec>["open"] | ElementEvents<import("../elements/search").SearchSpec>["open"];
      "close": ElementEvents<import("../elements/drawer").DrawerSpec>["close"] | ElementEvents<import("../elements/menu").MenuSpec>["close"] | ElementEvents<import("../elements/fab-menu").FabMenuSpec>["close"] | ElementEvents<import("../elements/snackbar").SnackbarSpec>["close"] | ElementEvents<import("../elements/dialog").DialogSpec>["close"] | ElementEvents<import("../elements/bottom-sheet").BottomSheetSpec>["close"] | ElementEvents<import("../elements/side-sheet").SideSheetSpec>["close"] | ElementEvents<import("../elements/datepicker").DatepickerSpec>["close"] | ElementEvents<import("../elements/timepicker").TimepickerSpec>["close"] | ElementEvents<import("../elements/search").SearchSpec>["close"];
      "action": ElementEvents<import("../elements/button-group").ButtonGroupSpec>["action"] | ElementEvents<import("../elements/snackbar").SnackbarSpec>["action"] | ElementEvents<import("../elements/search").SearchSpec>["action"];
      "remove": ElementEvents<import("../elements/chips").ChipsSpec>["remove"];
      "activate": ElementEvents<import("../elements/list").ListSpec>["activate"];
      "select": ElementEvents<import("../elements/menu").MenuSpec>["select"] | ElementEvents<import("../elements/fab-menu").FabMenuSpec>["select"] | ElementEvents<import("../elements/split-button").SplitButtonSpec>["select"] | ElementEvents<import("../elements/search").SearchSpec>["select"];
      "show": ElementEvents<import("../elements/toolbar").ToolbarSpec>["show"];
      "hide": ElementEvents<import("../elements/toolbar").ToolbarSpec>["hide"];
      "cancel": ElementEvents<import("../elements/dialog").DialogSpec>["cancel"];
      "confirm": ElementEvents<import("../elements/timepicker").TimepickerSpec>["confirm"];
    }
  }
}
