// src/solid/list.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/list";
import { listElement, defineList, type ListSpec, type ListElement } from "../elements/list";
import { createComponent, type MComponent } from "./create";

export const List: MComponent<ListSpec, ListElement> = /*#__PURE__*/ createComponent(listElement.spec, defineList, "List");
