// src/solid/loading-indicator.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/loading-indicator";
import { loadingIndicatorElement, defineLoadingIndicator, type LoadingIndicatorSpec, type LoadingIndicatorElement } from "../elements/loading-indicator";
import { createComponent, type MComponent } from "./create";

export const LoadingIndicator: MComponent<LoadingIndicatorSpec, LoadingIndicatorElement> = /*#__PURE__*/ createComponent(loadingIndicatorElement.spec, defineLoadingIndicator, "LoadingIndicator");
