// src/solid/navigation-bar.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/navigation-bar";
import { navigationBarElement, defineNavigationBar, type NavigationBarSpec, type NavigationBarElement } from "../elements/navigation-bar";
import { createComponent, type MComponent } from "./create";

export const NavigationBar: MComponent<NavigationBarSpec, NavigationBarElement> = /*#__PURE__*/ createComponent(navigationBarElement.spec, defineNavigationBar, "NavigationBar");
