// src/solid/navigation-rail-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { navigationRailItemDeclaration, type NavigationRailItemAttributes } from "../elements/navigation-rail";
import { createDeclaration, type MDeclaration } from "./create";

export const NavigationRailItem: MDeclaration<NavigationRailItemAttributes> = /*#__PURE__*/ createDeclaration(navigationRailItemDeclaration, "NavigationRailItem");
