// src/solid/progress.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/progress";
import { progressElement, defineProgress, type ProgressSpec, type ProgressElement } from "../elements/progress";
import { createComponent, type MComponent } from "./create";

export const Progress: MComponent<ProgressSpec, ProgressElement> = /*#__PURE__*/ createComponent(progressElement.spec, defineProgress, "Progress");
