// src/solid/select.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/textfield";
import "mtrl/elements/css/menu";
import "mtrl/elements/css/select";
import { selectElement, defineSelect, type SelectSpec, type SelectElement } from "../elements/select";
import { createComponent, type MComponent } from "./create";

export const Select: MComponent<SelectSpec, SelectElement> = /*#__PURE__*/ createComponent(selectElement.spec, defineSelect, "Select");
