// src/solid/shadow.ts
// Generated by scripts/generate-adapters.ts. Do not edit.
import type { JSX } from "solid-js";
import { isServer } from "solid-js/web";
import { getPrefix } from "../elements/adapter";

type Renderer = (
  tag: string,
  props: Record<string, unknown>,
  children: JSX.Element,
  prefix: string,
) => JSX.Element;

/** Host children with a declarative shadow template when the server renderer is registered. */
export const shadow = (tag: string, props: Record<string, unknown>, children: JSX.Element): JSX.Element => {
  if (!isServer) return children;
  const render = (globalThis as unknown as Record<symbol, { solid?: Renderer } | undefined>)[Symbol.for("mtrl.ssr")]?.solid;
  if (!render) return children;
  return render(tag, props, children, getPrefix());
};
