// src/solid/shadow.ts
// Generated by scripts/generate-adapters.ts. Do not edit.
import type { JSX } from "solid-js";
import { isServer } from "solid-js/web";
import { getPrefix } from "../elements/adapter";

type Renderer = (
  tag: string,
  props: Record<string, unknown>,
  children: () => JSX.Element,
  prefix: string,
) => string;

/** Declarative shadow template for one host, or "" in the browser and when no renderer is registered. */
export const shadow = (tag: string, props: Record<string, unknown>, children: () => JSX.Element): string => {
  if (!isServer) return "";
  const render = (globalThis as unknown as Record<symbol, { solid?: Renderer } | undefined>)[Symbol.for("mtrl.ssr")]?.solid;
  if (!render) return "";
  return render(tag, props, children, getPrefix());
};
