// src/solid/snackbar.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/progress";
import "material/elements/css/button";
import "material/elements/css/icon-button";
import "material/elements/css/snackbar";
import { snackbarElement, defineSnackbar, type SnackbarSpec, type SnackbarElement } from "../elements/snackbar";
import { createComponent, type MComponent } from "./create";

export const Snackbar: MComponent<SnackbarSpec, SnackbarElement> = /*#__PURE__*/ createComponent(snackbarElement.spec, defineSnackbar, "Snackbar");
