// src/solid/switch.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/switch";
import { switchElement, defineSwitch, type SwitchSpec, type SwitchElement } from "../elements/switch";
import { createComponent, type MComponent } from "./create";

export const Switch: MComponent<SwitchSpec, SwitchElement> = /*#__PURE__*/ createComponent(switchElement.spec, defineSwitch, "Switch");
