// src/solid/tabs.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/badge";
import "material/elements/css/progress";
import "material/elements/css/button";
import "material/elements/css/tabs";
import { tabsElement, defineTabs, type TabsSpec, type TabsElement } from "../elements/tabs";
import { createComponent, type MComponent } from "./create";

export const Tabs: MComponent<TabsSpec, TabsElement> = /*#__PURE__*/ createComponent(tabsElement.spec, defineTabs, "Tabs");
