// src/solid/textfield.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/textfield";
import { textfieldElement, defineTextfield, type TextfieldSpec, type TextfieldElement } from "../elements/textfield";
import { createComponent, type MComponent } from "./create";

export const Textfield: MComponent<TextfieldSpec, TextfieldElement> = /*#__PURE__*/ createComponent(textfieldElement.spec, defineTextfield, "Textfield");
