// src/solid/toolbar.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/icon-button";
import "material/elements/css/toolbar";
import { toolbarElement, defineToolbar, type ToolbarSpec, type ToolbarElement } from "../elements/toolbar";
import { createComponent, type MComponent } from "./create";

export const Toolbar: MComponent<ToolbarSpec, ToolbarElement> = /*#__PURE__*/ createComponent(toolbarElement.spec, defineToolbar, "Toolbar");
