// src/vue/badge.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/badge";
import { badgeElement, defineBadge, type BadgeSpec, type BadgeElement } from "../elements/badge";
import { createComponent, type MComponent } from "./create";

export const MBadge: MComponent<BadgeSpec, BadgeElement> = /*#__PURE__*/ createComponent(badgeElement.spec, defineBadge, "MBadge");
