// src/vue/bottom-app-bar.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/bottom-app-bar";
import { bottomAppBarElement, defineBottomAppBar, type BottomAppBarSpec, type BottomAppBarElement } from "../elements/bottom-app-bar";
import { createComponent, type MComponent } from "./create";

export const MBottomAppBar: MComponent<BottomAppBarSpec, BottomAppBarElement> = /*#__PURE__*/ createComponent(bottomAppBarElement.spec, defineBottomAppBar, "MBottomAppBar");
