// src/vue/bottom-sheet.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/bottom-sheet";
import { bottomSheetElement, defineBottomSheet, type BottomSheetSpec, type BottomSheetElement } from "../elements/bottom-sheet";
import { createComponent, type MComponent } from "./create";

export const MBottomSheet: MComponent<BottomSheetSpec, BottomSheetElement> = /*#__PURE__*/ createComponent(bottomSheetElement.spec, defineBottomSheet, "MBottomSheet");
