// src/vue/button-group.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/progress";
import "material/elements/css/button";
import "material/elements/css/icon-button";
import "material/elements/css/button-group";
import { buttonGroupElement, defineButtonGroup, type ButtonGroupSpec, type ButtonGroupElement } from "../elements/button-group";
import { createComponent, type MComponent } from "./create";

export const MButtonGroup: MComponent<ButtonGroupSpec, ButtonGroupElement> = /*#__PURE__*/ createComponent(buttonGroupElement.spec, defineButtonGroup, "MButtonGroup");
