// src/vue/button.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/progress";
import "mtrl/elements/css/button";
import { buttonElement, defineButton, type ButtonSpec, type ButtonElement } from "../elements/button";
import { createComponent, type MComponent } from "./create";

export const MButton: MComponent<ButtonSpec, ButtonElement> = /*#__PURE__*/ createComponent(buttonElement.spec, defineButton, "MButton");
