// src/vue/chip.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { chipDeclaration, type ChipAttributes } from "../elements/chips";
import { createDeclaration, type MDeclaration } from "./create";

export const MChip: MDeclaration<ChipAttributes> = /*#__PURE__*/ createDeclaration(chipDeclaration, "MChip");
