// src/vue/drawer.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/drawer";
import { drawerElement, defineDrawer, type DrawerSpec, type DrawerElement } from "../elements/drawer";
import { createComponent, type MComponent } from "./create";

export const MDrawer: MComponent<DrawerSpec, DrawerElement> = /*#__PURE__*/ createComponent(drawerElement.spec, defineDrawer, "MDrawer");
