// src/vue/drawer-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { drawerItemDeclaration, type DrawerItemAttributes } from "../elements/drawer";
import { createDeclaration, type MDeclaration } from "./create";

export const MDrawerItem: MDeclaration<DrawerItemAttributes> = /*#__PURE__*/ createDeclaration(drawerItemDeclaration, "MDrawerItem");
