// src/vue/fab.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/fab";
import { fabElement, defineFab, type FabSpec, type FabElement } from "../elements/fab";
import { createComponent, type MComponent } from "./create";

export const MFab: MComponent<FabSpec, FabElement> = /*#__PURE__*/ createComponent(fabElement.spec, defineFab, "MFab");
