// src/vue/index.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
/**
 * Vue components for the elements. Each renders its `<m-*>` tag, registers
 * it on mount and loads its CSS. `v-model` binds the element's live state.
 *
 * @module vue
 */

import "mtrl/elements/css/progress";
import "mtrl/elements/css/button";
import "mtrl/elements/css/switch";
import "mtrl/elements/css/badge";
import "mtrl/elements/css/tabs";
import "mtrl/elements/css/loading-indicator";
import "mtrl/elements/css/divider";
import "mtrl/elements/css/icon-button";
import "mtrl/elements/css/fab";
import "mtrl/elements/css/extended-fab";
import "mtrl/elements/css/checkbox";
import "mtrl/elements/css/slider";
import "mtrl/elements/css/textfield";
import "mtrl/elements/css/radios";
import "mtrl/elements/css/navigation-rail";
import "mtrl/elements/css/drawer";
import "mtrl/elements/css/top-app-bar";
import "mtrl/elements/css/bottom-app-bar";
import {
  buttonElement,
  defineButton,
  switchElement,
  defineSwitch,
  tabsElement,
  defineTabs,
  progressElement,
  defineProgress,
  loadingIndicatorElement,
  defineLoadingIndicator,
  badgeElement,
  defineBadge,
  dividerElement,
  defineDivider,
  iconButtonElement,
  defineIconButton,
  fabElement,
  defineFab,
  extendedFabElement,
  defineExtendedFab,
  checkboxElement,
  defineCheckbox,
  sliderElement,
  defineSlider,
  textfieldElement,
  defineTextfield,
  radiosElement,
  defineRadios,
  navigationRailElement,
  defineNavigationRail,
  drawerElement,
  defineDrawer,
  topAppBarElement,
  defineTopAppBar,
  bottomAppBarElement,
  defineBottomAppBar,
  tabDeclaration,
  radioDeclaration,
  navigationRailItemDeclaration,
  drawerItemDeclaration,
} from "../elements";
import type {
  ButtonSpec,
  ButtonElement,
  SwitchSpec,
  SwitchElement,
  TabsSpec,
  TabsElement,
  ProgressSpec,
  ProgressElement,
  LoadingIndicatorSpec,
  LoadingIndicatorElement,
  BadgeSpec,
  BadgeElement,
  DividerSpec,
  DividerElement,
  IconButtonSpec,
  IconButtonElement,
  FabSpec,
  FabElement,
  ExtendedFabSpec,
  ExtendedFabElement,
  CheckboxSpec,
  CheckboxElement,
  SliderSpec,
  SliderElement,
  TextfieldSpec,
  TextfieldElement,
  RadiosSpec,
  RadiosElement,
  NavigationRailSpec,
  NavigationRailElement,
  DrawerSpec,
  DrawerElement,
  TopAppBarSpec,
  TopAppBarElement,
  BottomAppBarSpec,
  BottomAppBarElement,
  TabAttributes,
  RadioAttributes,
  NavigationRailItemAttributes,
  DrawerItemAttributes,
} from "../elements";
import { createComponent, createDeclaration, type MComponent, type MDeclaration } from "./create";

export { configure } from "./create";
export type { VueProps, VueEmits, ModelProps, Exposed, MComponent, MDeclaration } from "./create";

export const MButton: MComponent<ButtonSpec, ButtonElement> = createComponent(buttonElement.spec, defineButton, "MButton");
export const MSwitch: MComponent<SwitchSpec, SwitchElement> = createComponent(switchElement.spec, defineSwitch, "MSwitch");
export const MTabs: MComponent<TabsSpec, TabsElement> = createComponent(tabsElement.spec, defineTabs, "MTabs");
export const MProgress: MComponent<ProgressSpec, ProgressElement> = createComponent(progressElement.spec, defineProgress, "MProgress");
export const MLoadingIndicator: MComponent<LoadingIndicatorSpec, LoadingIndicatorElement> = createComponent(loadingIndicatorElement.spec, defineLoadingIndicator, "MLoadingIndicator");
export const MBadge: MComponent<BadgeSpec, BadgeElement> = createComponent(badgeElement.spec, defineBadge, "MBadge");
export const MDivider: MComponent<DividerSpec, DividerElement> = createComponent(dividerElement.spec, defineDivider, "MDivider");
export const MIconButton: MComponent<IconButtonSpec, IconButtonElement> = createComponent(iconButtonElement.spec, defineIconButton, "MIconButton");
export const MFab: MComponent<FabSpec, FabElement> = createComponent(fabElement.spec, defineFab, "MFab");
export const MExtendedFab: MComponent<ExtendedFabSpec, ExtendedFabElement> = createComponent(extendedFabElement.spec, defineExtendedFab, "MExtendedFab");
export const MCheckbox: MComponent<CheckboxSpec, CheckboxElement> = createComponent(checkboxElement.spec, defineCheckbox, "MCheckbox");
export const MSlider: MComponent<SliderSpec, SliderElement> = createComponent(sliderElement.spec, defineSlider, "MSlider");
export const MTextfield: MComponent<TextfieldSpec, TextfieldElement> = createComponent(textfieldElement.spec, defineTextfield, "MTextfield");
export const MRadios: MComponent<RadiosSpec, RadiosElement> = createComponent(radiosElement.spec, defineRadios, "MRadios");
export const MNavigationRail: MComponent<NavigationRailSpec, NavigationRailElement> = createComponent(navigationRailElement.spec, defineNavigationRail, "MNavigationRail");
export const MDrawer: MComponent<DrawerSpec, DrawerElement> = createComponent(drawerElement.spec, defineDrawer, "MDrawer");
export const MTopAppBar: MComponent<TopAppBarSpec, TopAppBarElement> = createComponent(topAppBarElement.spec, defineTopAppBar, "MTopAppBar");
export const MBottomAppBar: MComponent<BottomAppBarSpec, BottomAppBarElement> = createComponent(bottomAppBarElement.spec, defineBottomAppBar, "MBottomAppBar");
export const MTab: MDeclaration<TabAttributes> = createDeclaration(tabDeclaration, "MTab");
export const MRadio: MDeclaration<RadioAttributes> = createDeclaration(radioDeclaration, "MRadio");
export const MNavigationRailItem: MDeclaration<NavigationRailItemAttributes> = createDeclaration(navigationRailItemDeclaration, "MNavigationRailItem");
export const MDrawerItem: MDeclaration<DrawerItemAttributes> = createDeclaration(drawerItemDeclaration, "MDrawerItem");
