// src/vue/index.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
/**
 * Vue components for the elements. Each renders its `<m-*>` tag, registers
 * it on mount and loads its CSS. `v-model` binds the element's live state.
 *
 * @module vue
 */

import "mtrl/elements/css/progress";
import "mtrl/elements/css/button";
import "mtrl/elements/css/switch";
import "mtrl/elements/css/badge";
import "mtrl/elements/css/tabs";
import {
  buttonElement,
  defineButton,
  switchElement,
  defineSwitch,
  tabsElement,
  defineTabs,
  tabDeclaration,
} from "../elements";
import type {
  ButtonSpec,
  ButtonElement,
  SwitchSpec,
  SwitchElement,
  TabsSpec,
  TabsElement,
  TabAttributes,
} from "../elements";
import { createComponent, createDeclaration, type MComponent, type MDeclaration } from "./create";

export { configure } from "./create";
export type { VueProps, VueEmits, ModelProps, Exposed, MComponent, MDeclaration } from "./create";

export const MButton: MComponent<ButtonSpec, ButtonElement> = createComponent(buttonElement.spec, defineButton, "MButton");
export const MSwitch: MComponent<SwitchSpec, SwitchElement> = createComponent(switchElement.spec, defineSwitch, "MSwitch");
export const MTabs: MComponent<TabsSpec, TabsElement> = createComponent(tabsElement.spec, defineTabs, "MTabs");
export const MTab: MDeclaration<TabAttributes> = createDeclaration(tabDeclaration, "MTab");
