// src/vue/list-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { listItemDeclaration, type ListItemAttributes } from "../elements/list";
import { createDeclaration, type MDeclaration } from "./create";

export const MListItem: MDeclaration<ListItemAttributes> = /*#__PURE__*/ createDeclaration(listItemDeclaration, "MListItem");
