// src/vue/loading-indicator.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/loading-indicator";
import { loadingIndicatorElement, defineLoadingIndicator, type LoadingIndicatorSpec, type LoadingIndicatorElement } from "../elements/loading-indicator";
import { createComponent, type MComponent } from "./create";

export const MLoadingIndicator: MComponent<LoadingIndicatorSpec, LoadingIndicatorElement> = /*#__PURE__*/ createComponent(loadingIndicatorElement.spec, defineLoadingIndicator, "MLoadingIndicator");
