// src/vue/menu.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/menu";
import { menuElement, defineMenu, type MenuSpec, type MenuElement } from "../elements/menu";
import { createComponent, type MComponent } from "./create";

export const MMenu: MComponent<MenuSpec, MenuElement> = /*#__PURE__*/ createComponent(menuElement.spec, defineMenu, "MMenu");
