// src/vue/menu-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { menuItemDeclaration, type MenuItemAttributes } from "../elements/menu";
import { createDeclaration, type MDeclaration } from "./create";

export const MMenuItem: MDeclaration<MenuItemAttributes> = /*#__PURE__*/ createDeclaration(menuItemDeclaration, "MMenuItem");
