// src/vue/progress.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/progress";
import { progressElement, defineProgress, type ProgressSpec, type ProgressElement } from "../elements/progress";
import { createComponent, type MComponent } from "./create";

export const MProgress: MComponent<ProgressSpec, ProgressElement> = /*#__PURE__*/ createComponent(progressElement.spec, defineProgress, "MProgress");
