// src/vue/radio.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { radioDeclaration, type RadioAttributes } from "../elements/radios";
import { createDeclaration, type MDeclaration } from "./create";

export const MRadio: MDeclaration<RadioAttributes> = /*#__PURE__*/ createDeclaration(radioDeclaration, "MRadio");
