// src/vue/search-suggestion.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { searchSuggestionDeclaration, type SearchSuggestionAttributes } from "../elements/search";
import { createDeclaration, type MDeclaration } from "./create";

export const MSearchSuggestion: MDeclaration<SearchSuggestionAttributes> = /*#__PURE__*/ createDeclaration(searchSuggestionDeclaration, "MSearchSuggestion");
