// src/vue/search.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/search";
import { searchElement, defineSearch, type SearchSpec, type SearchElement } from "../elements/search";
import { createComponent, type MComponent } from "./create";

export const MSearch: MComponent<SearchSpec, SearchElement> = /*#__PURE__*/ createComponent(searchElement.spec, defineSearch, "MSearch");
