// src/vue/select-option.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { selectOptionDeclaration, type SelectOptionAttributes } from "../elements/select";
import { createDeclaration, type MDeclaration } from "./create";

export const MSelectOption: MDeclaration<SelectOptionAttributes> = /*#__PURE__*/ createDeclaration(selectOptionDeclaration, "MSelectOption");
