// src/vue/shadow.ts
// Generated by scripts/generate-adapters.ts. Do not edit.
import type { VNode } from "vue";
import { getPrefix, isBrowser } from "../elements/adapter";

type Renderer = (
  tag: string,
  props: Record<string, unknown>,
  children: () => VNode[],
  prefix: string,
) => string;

/** Declarative shadow template for one host, or "" in the browser and when no renderer is registered. */
export const shadow = (tag: string, props: Record<string, unknown>, children: () => VNode[]): string => {
  if (isBrowser) return "";
  const render = (globalThis as unknown as Record<symbol, { vue?: Renderer } | undefined>)[Symbol.for("mtrl.ssr")]?.vue;
  if (!render) return "";
  return render(tag, props, children, getPrefix());
};
