// src/vue/side-sheet.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/side-sheet";
import { sideSheetElement, defineSideSheet, type SideSheetSpec, type SideSheetElement } from "../elements/side-sheet";
import { createComponent, type MComponent } from "./create";

export const MSideSheet: MComponent<SideSheetSpec, SideSheetElement> = /*#__PURE__*/ createComponent(sideSheetElement.spec, defineSideSheet, "MSideSheet");
