// src/vue/slider.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/slider";
import { sliderElement, defineSlider, type SliderSpec, type SliderElement } from "../elements/slider";
import { createComponent, type MComponent } from "./create";

export const MSlider: MComponent<SliderSpec, SliderElement> = /*#__PURE__*/ createComponent(sliderElement.spec, defineSlider, "MSlider");
