// src/vue/split-button.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "material/elements/css/progress";
import "material/elements/css/button";
import "material/elements/css/menu";
import "material/elements/css/split-button";
import { splitButtonElement, defineSplitButton, type SplitButtonSpec, type SplitButtonElement } from "../elements/split-button";
import { createComponent, type MComponent } from "./create";

export const MSplitButton: MComponent<SplitButtonSpec, SplitButtonElement> = /*#__PURE__*/ createComponent(splitButtonElement.spec, defineSplitButton, "MSplitButton");
