// src/vue/tab.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import { tabDeclaration, type TabAttributes } from "../elements/tabs";
import { createDeclaration, type MDeclaration } from "./create";

export const MTab: MDeclaration<TabAttributes> = /*#__PURE__*/ createDeclaration(tabDeclaration, "MTab");
