// src/vue/text-field.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/text-field";
import { textFieldElement, defineTextField, type TextFieldSpec, type TextFieldElement } from "../elements/text-field";
import { createComponent, type MComponent } from "./create";

export const MTextField: MComponent<TextFieldSpec, TextFieldElement> = /*#__PURE__*/ createComponent(textFieldElement.spec, defineTextField, "MTextField");
