// src/vue/toolbar.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/icon-button";
import "mtrl/elements/css/toolbar";
import { toolbarElement, defineToolbar, type ToolbarSpec, type ToolbarElement } from "../elements/toolbar";
import { createComponent, type MComponent } from "./create";

export const MToolbar: MComponent<ToolbarSpec, ToolbarElement> = /*#__PURE__*/ createComponent(toolbarElement.spec, defineToolbar, "MToolbar");
