// src/vue/tooltip.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/tooltip";
import { tooltipElement, defineTooltip, type TooltipSpec, type TooltipElement } from "../elements/tooltip";
import { createComponent, type MComponent } from "./create";

export const MTooltip: MComponent<TooltipSpec, TooltipElement> = /*#__PURE__*/ createComponent(tooltipElement.spec, defineTooltip, "MTooltip");
