// src/vue/top-app-bar.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
import "mtrl/elements/css/top-app-bar";
import { topAppBarElement, defineTopAppBar, type TopAppBarSpec, type TopAppBarElement } from "../elements/top-app-bar";
import { createComponent, type MComponent } from "./create";

export const MTopAppBar: MComponent<TopAppBarSpec, TopAppBarElement> = /*#__PURE__*/ createComponent(topAppBarElement.spec, defineTopAppBar, "MTopAppBar");
