#!/usr/bin/env bun
// Writes each framework adapter's index (src/react, src/solid, src/vue):
// one component per element and per declaration child, from the registry in
// src/elements/index.ts.
//
// Naming is by convention, and the compiler checks it: element `switch` has
// `switchElement`, `defineSwitch`, `SwitchSpec` and `SwitchElement`;
// declaration `tab` has `tabDeclaration` and `TabAttributes`.
//
//   bun run scripts/generate-adapters.ts           write the files
//   bun run scripts/generate-adapters.ts --check   fail if one is stale (CI)

import { elements, declarations } from "../src/elements";

const pascal = (name: string): string =>
  name.replace(/(^|-)([a-z])/g, (_, __: string, c: string) => c.toUpperCase());

interface Framework {
  dir: string;
  /** The exported component name for an element or declaration name. */
  component: (name: string) => string;
  header: string;
  /** Extra line at the top, such as a directive. */
  directive?: string;
  exports: string;
}

const frameworks: Framework[] = [
  {
    dir: "react",
    component: pascal,
    directive: '"use client";',
    header: "React components for the elements. Each renders its `<m-*>` tag, registers\n * it on first mount and loads its CSS.",
    exports: `export { configure } from "./create";
export type { ComponentProps, DeclarationProps, EventProps, DefaultProps, FormProps, MComponent, MDeclaration } from "./create";`,
  },
  {
    dir: "solid",
    component: pascal,
    header: "Solid components for the elements. Each renders its `<m-*>` tag, registers\n * it on mount and loads its CSS.",
    exports: `export { configure } from "./create";
export type { SolidProps, DeclarationProps, EventProps, DefaultProps, FormProps, MComponent, MDeclaration } from "./create";`,
  },
  {
    dir: "vue",
    component: (name) => `M${pascal(name)}`,
    header: "Vue components for the elements. Each renders its `<m-*>` tag, registers\n * it on mount and loads its CSS. `v-model` binds the element's live state.",
    exports: `export { configure } from "./create";
export type { VueProps, VueEmits, ModelProps, Exposed, MComponent, MDeclaration } from "./create";`,
  },
];

const css = [...new Set(Object.values(elements).flatMap((element) => [...element.spec.styles]))];
const names = Object.keys(elements);
const declared = Object.keys(declarations);

const render = (framework: Framework): string => `// src/${framework.dir}/index.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
${framework.directive ? `${framework.directive}\n` : ""}/**
 * ${framework.header}
 *
 * @module ${framework.dir}
 */

${css.map((name) => `import "mtrl/elements/css/${name}";`).join("\n")}
import {
${[
  ...names.flatMap((name) => [`${name}Element`, `define${pascal(name)}`]),
  ...declared.map((name) => `${name}Declaration`),
].map((id) => `  ${id},`).join("\n")}
} from "../elements";
import type {
${[
  ...names.flatMap((name) => [`${pascal(name)}Spec`, `${pascal(name)}Element`]),
  ...declared.map((name) => `${pascal(name)}Attributes`),
].map((id) => `  ${id},`).join("\n")}
} from "../elements";
import { createComponent, createDeclaration, type MComponent, type MDeclaration } from "./create";

${framework.exports}

${names
  .map((name) => {
    const P = pascal(name);
    return `export const ${framework.component(name)}: MComponent<${P}Spec, ${P}Element> = createComponent(${name}Element.spec, define${P}, "${framework.component(name)}");`;
  })
  .join("\n")}
${declared
  .map((name) => {
    const P = pascal(name);
    return `export const ${framework.component(name)}: MDeclaration<${P}Attributes> = createDeclaration(${name}Declaration, "${framework.component(name)}");`;
  })
  .join("\n")}
`;

const check = process.argv.includes("--check");
let stale = false;
for (const framework of frameworks) {
  const target = `src/${framework.dir}/index.ts`;
  const source = render(framework);
  if (check) {
    const current = await Bun.file(target).text().catch(() => "");
    if (current !== source) {
      console.error(`${target} is stale: run bun run adapters:generate`);
      stale = true;
    }
  } else {
    await Bun.write(target, source);
    console.log(`wrote ${target}`);
  }
}
if (stale) process.exit(1);
if (check) console.log("adapter indexes are up to date");
