#!/usr/bin/env bun
// Writes src/react/index.ts: one React component per element and per
// declaration child, from the registry in src/elements/index.ts.
//
// Naming is by convention, and the compiler checks it: element `switch` has
// `switchElement`, `defineSwitch`, `SwitchSpec` and `SwitchElement`;
// declaration `tab` has `tabDeclaration` and `TabAttributes`.
//
//   bun run scripts/generate-react.ts           write the file
//   bun run scripts/generate-react.ts --check   fail if it is stale (CI)

import { elements, declarations } from "../src/elements";

const target = "src/react/index.ts";
const pascal = (name: string): string =>
  name.replace(/(^|-)([a-z])/g, (_, __: string, c: string) => c.toUpperCase());

const css = [...new Set(Object.values(elements).flatMap((element) => [...element.spec.styles]))];
const names = Object.keys(elements);
const declared = Object.keys(declarations);

const source = `// src/react/index.ts
// Generated by scripts/generate-react.ts from src/elements. Do not edit.
"use client";
/**
 * React components for the elements. Each renders its \`<m-*>\` tag, registers
 * it on first mount and loads its CSS.
 *
 * @module react
 */

${css.map((name) => `import "mtrl/elements/css/${name}";`).join("\n")}
import {
${[
  ...names.flatMap((name) => [`${name}Element`, `define${pascal(name)}`]),
  ...declared.map((name) => `${name}Declaration`),
].map((id) => `  ${id},`).join("\n")}
} from "../elements";
import type {
${[
  ...names.flatMap((name) => [`${pascal(name)}Spec`, `${pascal(name)}Element`]),
  ...declared.map((name) => `${pascal(name)}Attributes`),
].map((id) => `  ${id},`).join("\n")}
} from "../elements";
import { createComponent, createDeclaration, type MComponent, type MDeclaration } from "./create";

export { configure } from "./create";
export type { ComponentProps, DeclarationProps, EventProps, DefaultProps, FormProps, MComponent, MDeclaration } from "./create";

${names
  .map((name) => {
    const P = pascal(name);
    return `export const ${P}: MComponent<${P}Spec, ${P}Element> = createComponent(${name}Element.spec, define${P}, "${P}");`;
  })
  .join("\n")}
${declared
  .map((name) => {
    const P = pascal(name);
    return `export const ${P}: MDeclaration<${P}Attributes> = createDeclaration(${name}Declaration, "${P}");`;
  })
  .join("\n")}
`;

if (process.argv.includes("--check")) {
  const current = await Bun.file(target).text().catch(() => "");
  if (current !== source) {
    console.error(`${target} is stale: run bun run scripts/generate-react.ts`);
    process.exit(1);
  }
  console.log(`${target} is up to date`);
} else {
  await Bun.write(target, source);
  console.log(`wrote ${target}`);
}
