#!/usr/bin/env bun
// Writes each framework adapter (src/react, src/solid, src/vue): one module
// per element and per declaration child, from the registry in
// src/elements/index.ts, and an index that re-exports them.
//
// Naming is by convention, and the compiler checks it: element `switch` has
// `switchElement`, `defineSwitch`, `SwitchSpec` and `SwitchElement`;
// declaration `tab` has `tabDeclaration` and `TabAttributes`.
//
//   bun run scripts/generate-adapters.ts           write the files
//   bun run scripts/generate-adapters.ts --check   fail if one is stale (CI)

import { readdirSync, unlinkSync } from "node:fs";
import { declarationModules, elementModules, kebab } from "./element-modules";

const pascal = (name: string): string =>
  name.replace(/(^|-)([a-z])/g, (_, __: string, c: string) => c.toUpperCase());

interface Framework {
  dir: string;
  /** The exported component name for an element or declaration name. */
  component: (name: string) => string;
  header: string;
  /** Extra line at the top, such as a directive. */
  directive?: string;
  exports: string;
}

const frameworks: Framework[] = [
  {
    dir: "react",
    component: pascal,
    directive: '"use client";',
    header: "React components for the elements. Each renders its `<m-*>` tag, registers\n * it on first mount and loads its CSS.",
    exports: `export { configure } from "./create";
export type { ComponentProps, DeclarationProps, EventProps, DefaultProps, FormProps, MComponent, MDeclaration } from "./create";`,
  },
  {
    dir: "solid",
    component: pascal,
    header: "Solid components for the elements. Each renders its `<m-*>` tag, registers\n * it on mount and loads its CSS.",
    exports: `export { configure } from "./create";
export type { SolidProps, DeclarationProps, EventProps, DefaultProps, FormProps, MComponent, MDeclaration } from "./create";`,
  },
  {
    dir: "vue",
    component: (name) => `M${pascal(name)}`,
    header: "Vue components for the elements. Each renders its `<m-*>` tag, registers\n * it on mount and loads its CSS. `v-model` binds the element's live state.",
    exports: `export { configure } from "./create";
export type { VueProps, VueEmits, VueSlots, ModelProps, Exposed, MComponent, MDeclaration } from "./create";`,
  },
];

// A component's own module (FLO-327): its element's CSS and element module
// only, so importing one component ships that component and nothing else.
// The index re-exports them, and the calls are pure, so a bundler drops what
// the app does not name.
const module = (framework: Framework, name: string, body: string, imports: string[]): string => `// src/${framework.dir}/${kebab(name)}.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
${framework.directive ? `${framework.directive}\n` : ""}${imports.join("\n")}

${body}
`;

const elementModule = (framework: Framework, { name, module: from, styles }: (typeof elementModules)[number]): string => {
  const P = pascal(name);
  const C = framework.component(name);
  return module(framework, name, `export const ${C}: MComponent<${P}Spec, ${P}Element> = /*#__PURE__*/ createComponent(${name}Element.spec, define${P}, "${C}");`, [
    ...styles.map((style) => `import "mtrl/elements/css/${style}";`),
    `import { ${name}Element, define${P}, type ${P}Spec, type ${P}Element } from "../elements/${from}";`,
    `import { createComponent, type MComponent } from "./create";`,
  ]);
};

const declarationModule = (framework: Framework, { name, module: from }: (typeof declarationModules)[number]): string => {
  const P = pascal(name);
  const C = framework.component(name);
  return module(framework, name, `export const ${C}: MDeclaration<${P}Attributes> = /*#__PURE__*/ createDeclaration(${name}Declaration, "${C}");`, [
    `import { ${name}Declaration, type ${P}Attributes } from "../elements/${from}";`,
    `import { createDeclaration, type MDeclaration } from "./create";`,
  ]);
};

const index = (framework: Framework): string => `// src/${framework.dir}/index.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
${framework.directive ? `${framework.directive}\n` : ""}/**
 * ${framework.header}
 *
 * @module ${framework.dir}
 */

${framework.exports}

${[...elementModules, ...declarationModules].map(({ name }) => `export { ${framework.component(name)} } from "./${kebab(name)}";`).join("\n")}
`;

/** Every file the generator owns, by path. */
const files = (framework: Framework): Map<string, string> => new Map([
  [`src/${framework.dir}/index.ts`, index(framework)],
  ...elementModules.map((element) => [`src/${framework.dir}/${kebab(element.name)}.ts`, elementModule(framework, element)] as const),
  ...declarationModules.map((declaration) => [`src/${framework.dir}/${kebab(declaration.name)}.ts`, declarationModule(framework, declaration)] as const),
]);

/** Hand-written files in an adapter folder; anything else there is generated. */
const OWN = new Set(["create.ts", "css.d.ts"]);

const check = process.argv.includes("--check");
let stale = false;
for (const framework of frameworks) {
  const expected = files(framework);
  const present = readdirSync(`src/${framework.dir}`).filter((file) => !OWN.has(file)).map((file) => `src/${framework.dir}/${file}`);
  for (const target of present.filter((file) => !expected.has(file))) {
    if (check) {
      console.error(`${target} is not generated any more: run bun run adapters:generate`);
      stale = true;
    } else {
      unlinkSync(target);
      console.log(`removed ${target}`);
    }
  }
  for (const [target, source] of expected) {
    if (check) {
      const current = await Bun.file(target).text().catch(() => "");
      if (current !== source) {
        console.error(`${target} is stale: run bun run adapters:generate`);
        stale = true;
      }
    } else {
      await Bun.write(target, source);
    }
  }
  if (!check) console.log(`wrote src/${framework.dir}: ${expected.size} files`);
}
if (stale) process.exit(1);
if (check) console.log("adapter modules are up to date");
