// Writes dist/svelte: one Svelte 5 component per element and per declaration
// child, from the registry in src/elements/index.ts, plus the entry point and
// the types. Svelte components must be .svelte files the app compiles, so the
// build writes them next to the compiled runtime (dist/svelte/runtime.js)
// rather than committing generated sources. Called by build.ts.
//
// Naming is by convention, as in scripts/generate-adapters.ts: element
// `switch` has `switchElement`, `defineSwitch` and `SwitchSpec`; declaration
// `tab` has `tabDeclaration` and `TabAttributes`.

import { mkdir, writeFile } from "node:fs/promises";
import { elements, declarations } from "../src/elements";

const pascal = (name: string): string =>
  name.replace(/(^|-)([a-z])/g, (_, __: string, c: string) => c.toUpperCase());

const HEADER = "<!-- Generated by mtrl's build (scripts/svelte-package.ts) from src/elements. -->";

const component = (name: string, live: string[]): string => {
  const P = pascal(name);
  // The setters' parameter is `next`: a live property of that name would
  // shadow it, as `value` once did.
  if (live.includes("next")) throw new Error(`${name}: a live property named "next" clashes with the generated setters`);
  const bindable = live.map((p) => `    ${p} = $bindable(),\n`).join("");
  const liveObject = `{ ${live.join(", ")} }`;
  const setters = `{ ${live.map((p) => `${p}: (next: unknown) => (${p} = next)`).join(", ")} }`;
  return `${HEADER}
<script lang="ts">
  import type { Snippet } from "svelte";
  import { ${name}Element, define${P} } from "../elements/index.js";
  import { adapter } from "./runtime.js";

  const runtime = adapter(${name}Element.spec, define${P});
  const action = runtime.action;
  let {
${bindable}    children,
    ...props
  }: { ${live.map((p) => `${p}?: unknown; `).join("")}children?: Snippet; [key: string]: unknown } = $props();
</script>

<svelte:element
  this={runtime.tag}
  {...runtime.attributes(props, ${liveObject})}
  use:action={{ props, live: ${liveObject}, set: ${setters} }}
>{@render children?.()}</svelte:element>
`;
};

const declarationComponent = (name: string): string => `${HEADER}
<script lang="ts">
  import type { Snippet } from "svelte";
  import { ${name}Declaration } from "../elements/index.js";
  import { declaration } from "./runtime.js";

  const runtime = declaration(${name}Declaration);
  let { children, ...props }: { children?: Snippet; [key: string]: unknown } = $props();
</script>

<svelte:element this={runtime.tag} {...runtime.attributes(props)}>{@render children?.()}</svelte:element>
`;

export async function emitSvelte(outdir: string): Promise<void> {
  const dir = `${outdir}/svelte`;
  await mkdir(dir, { recursive: true });
  const css = [...new Set(Object.values(elements).flatMap((element) => [...element.spec.styles]))];
  const exports: string[] = [];

  for (const [name, element] of Object.entries(elements)) {
    const P = pascal(name);
    const live = Object.keys(element.spec.properties ?? {});
    await writeFile(`${dir}/${P}.svelte`, component(name, live));
    await writeFile(`${dir}/${P}.svelte.d.ts`, `import type { Component } from "svelte";
import type { ${P}Spec } from "../elements/index.js";
import type { Bindable, SvelteProps } from "./runtime.js";
declare const ${P}: Component<SvelteProps<${P}Spec>, Record<string, never>, Bindable<${P}Spec>>;
export default ${P};
`);
    exports.push(`export { default as ${P} } from "./${P}.svelte";`);
  }
  for (const name of Object.keys(declarations)) {
    const P = pascal(name);
    await writeFile(`${dir}/${P}.svelte`, declarationComponent(name));
    await writeFile(`${dir}/${P}.svelte.d.ts`, `import type { Component } from "svelte";
import type { ${P}Attributes } from "../elements/index.js";
import type { DeclarationProps } from "./runtime.js";
declare const ${P}: Component<DeclarationProps<${P}Attributes>>;
export default ${P};
`);
    exports.push(`export { default as ${P} } from "./${P}.svelte";`);
  }

  const cssImports = css.map((name) => `import "mtrl/elements/css/${name}";`).join("\n");
  await writeFile(`${dir}/index.js`, `// Generated by mtrl's build (scripts/svelte-package.ts) from src/elements.
${cssImports}
${exports.join("\n")}
export { configure } from "./runtime.js";
`);
  await writeFile(`${dir}/index.d.ts`, `${exports.join("\n")}
export { configure } from "./runtime.js";
export type { SvelteProps, EventProps, Bindable, DeclarationProps, Binding } from "./runtime.js";
`);
}
