// Writes dist/svelte: one Svelte 5 component per element and per declaration
// child, from the registry in src/elements/index.ts, plus the entry point and
// the types. Svelte components must be .svelte files the app compiles, so the
// build writes them next to the compiled runtime (dist/svelte/runtime.js)
// rather than committing generated sources. Called by scripts/build.ts.
//
// Naming is by convention, as in scripts/generate-adapters.ts: element
// `switch` has `switchElement`, `defineSwitch` and `SwitchSpec`; declaration
// `tab` has `tabDeclaration` and `TabAttributes`.

import { mkdir, writeFile } from "node:fs/promises";
import { elements } from "../src/elements";
import { declarationModules, elementModules } from "./element-modules";

const pascal = (name: string): string =>
  name.replace(/(^|-)([a-z])/g, (_, __: string, c: string) => c.toUpperCase());

const HEADER = "<!-- Generated by mtrl's build (scripts/svelte-package.ts) from src/elements. -->";

// Each component imports its own element module and CSS, not the registry
// (FLO-327): the index only re-exports, so an app ships what it names.
const component = (name: string, live: string[], from: string, styles: string[]): string => {
  const P = pascal(name);
  // The setters' parameter is `next`: a live property of that name would
  // shadow it, as `value` once did.
  if (live.includes("next")) throw new Error(`${name}: a live property named "next" clashes with the generated setters`);
  const bindable = live.map((p) => `    ${p} = $bindable(),\n`).join("");
  const liveObject = `{ ${live.join(", ")} }`;
  const setters = `{ ${live.map((p) => `${p}: (next: unknown) => (${p} = next)`).join(", ")} }`;
  // Every host can emit a declarative shadow root (FLO-375). The value is ""
  // in the browser and for opted-out elements, so `{#if}` renders nothing
  // where the parser already consumed the template. `props` and `children`
  // stay inside `$derived`: reading them while the script runs is a warning.
  return `${HEADER}
<script lang="ts">
  import type { Snippet } from "svelte";
${styles.map((style) => `  import "mtrl/elements/css/${style}";\n`).join("")}  import { ${name}Element, define${P} } from "../elements/${from}.js";
  import { adapter, shadowMarkup } from "./runtime.js";

  const runtime = adapter(${name}Element.spec, define${P});
  const action = runtime.action;
  let {
${bindable}    children,
    ...props
  }: { ${live.map((p) => `${p}?: unknown; `).join("")}children?: Snippet; [key: string]: unknown } = $props();
  // \`bind:this\` on the component reads \`element\`, as Vue's template ref does (FLO-325).
  let node = $state<HTMLElement | null>(null);
  export { node as element };
  let shadow = $derived(shadowMarkup(runtime, props, children, ${liveObject}));
</script>

<svelte:element
  this={runtime.tag}
  bind:this={node}
  {...runtime.attributes(props, ${liveObject})}
  use:action={{ props, live: ${liveObject}, set: ${setters} }}
>{#if shadow}{@html shadow}{/if}{@render children?.()}{#each runtime.snippets(props) as [slot, snippet] (slot)}<span style="display: contents" {...{ slot }}>{@render snippet()}</span>{/each}</svelte:element>
`;
};

const declarationComponent = (name: string, from: string): string => `${HEADER}
<script lang="ts">
  import type { Snippet } from "svelte";
  import { ${name}Declaration } from "../elements/${from}.js";
  import { declaration } from "./runtime.js";

  const runtime = declaration(${name}Declaration);
  let { children, ...props }: { children?: Snippet; [key: string]: unknown } = $props();
</script>

<svelte:element this={runtime.tag} {...runtime.attributes(props)}>{@render children?.()}</svelte:element>
`;

/** The source `emitSvelte` writes for one element. Tests read it without a build. */
export const componentSource = component;

/** The source `emitSvelte` writes for one declaration child. */
export const declarationSource = declarationComponent;

export async function emitSvelte(outdir: string): Promise<void> {
  const dir = `${outdir}/svelte`;
  await mkdir(dir, { recursive: true });
  const exports: string[] = [];

  for (const { name, module, styles } of elementModules) {
    const P = pascal(name);
    const live = Object.keys(elements[name as keyof typeof elements].spec.properties ?? {});
    await writeFile(`${dir}/${P}.svelte`, component(name, live, module, styles));
    await writeFile(`${dir}/${P}.svelte.d.ts`, `import type { Component } from "svelte";
import type { ${P}Spec, ${P}Element } from "../elements/index.js";
import type { Bindable, SvelteProps } from "./runtime.js";
declare const ${P}: Component<SvelteProps<${P}Spec>, { readonly element: ${P}Element | null }, Bindable<${P}Spec>>;
export default ${P};
`);
    exports.push(`export { default as ${P} } from "./${P}.svelte";`);
  }
  for (const { name, module } of declarationModules) {
    const P = pascal(name);
    await writeFile(`${dir}/${P}.svelte`, declarationComponent(name, module));
    await writeFile(`${dir}/${P}.svelte.d.ts`, `import type { Component } from "svelte";
import type { ${P}Attributes } from "../elements/index.js";
import type { DeclarationProps } from "./runtime.js";
declare const ${P}: Component<DeclarationProps<${P}Attributes>>;
export default ${P};
`);
    exports.push(`export { default as ${P} } from "./${P}.svelte";`);
  }

  await writeFile(`${dir}/index.js`, `// Generated by mtrl's build (scripts/svelte-package.ts) from src/elements.
${exports.join("\n")}
export { configure } from "./runtime.js";
`);
  await writeFile(`${dir}/index.d.ts`, `${exports.join("\n")}
export { configure } from "./runtime.js";
export type { SvelteProps, EventProps, Bindable, DeclarationProps, Binding } from "./runtime.js";
`);
}
