// Explicit remainder of the text-field rename, after the seven patterns.
// Each entry names a file, the exact text, and either the replacement or
// keep. A missing old text on a later tree fails the run by this id.
// Generated from origin/next 8fb21d72. Do not hand-edit a generated file
// from here; this list is the hand classification.

export interface RenameEntry {
  id: string;
  file: string;
  old: string;
  new: string;
  action: "replace" | "keep";
  kind: "line" | "block";
  reason: string;
}

export const entries: RenameEntry[] = [
  {
    id: "block-delete-canonical",
    file: "scripts/element-modules.ts",
    old: "/**\n * Identifiers that write a word boundary the element's name does not (FLO-383):\n * the element `text-field` (tag `m-text-field`) is `TextField` in every exported\n * identifier, as M3 writes \"text field\" as two words. Tags, module files and the\n * registry key keep the element's name.\n */\nconst CANONICAL: Record<string, string> = { textfield: \"TextField\" };\n\n/** `navigationRail` → `NavigationRail`; `text-field` → `TextField` (FLO-383). */\nexport const pascal = (name: string): string =>\n  CANONICAL[name] ?? name.replace(/(^|-)([a-z])/g, (_, __: string, c: string) => c.toUpperCase());\n\n/** `navigationRail` → `navigationRail`; `text-field` → `textField`, as the element's exports are named. */\nexport const camel = (name: string): string => pascal(name).replace(/^[A-Z]/, (c) => c.toLowerCase());",
    new: "/** `navigationRail` → `NavigationRail`. A camelCase key such as `textField` becomes `TextField`. */\nexport const pascal = (name: string): string =>\n  name.replace(/(^|-)([a-z])/g, (_, __: string, c: string) => c.toUpperCase());\n\n/** `navigationRail` → `navigationRail`. */\nexport const camel = (name: string): string => pascal(name).replace(/^[A-Z]/, (c) => c.toLowerCase());",
    action: "replace",
    kind: "block",
    reason: "pascal(textField) is already TextField, so the textfield special case is deleted",
  },
  {
    id: "block-canonical-header",
    file: "test/canonical-text-field.test.ts",
    old: "// test/canonical-text-field.test.ts\n//\n// FLO-383 PR B: every exported identifier writes \"text field\" as two words.\n// 0.10.5 exported both spellings (A2); 1.0 has only the canonical ones. String\n// values stay: the <m-text-field> tag, CSS classes, event strings and the\n// constants' values. Svelte's index is written by the build; svelte:check\n// covers it. Read with the type checker, so nothing here needs a build.",
    new: "// test/canonical-text-field.test.ts\n//\n// FLO-383: every exported identifier writes \"text field\" as two words.\n// 0.10.5 exported both spellings; 3.0.0 has only the canonical ones. The strings\n// follow (FLO-560): the tag, the classes and the constants' values are\n// text-field too. The list below pins that the old identifier spellings are\n// gone. The guard under it pins that the one-word spelling does not return.",
    action: "replace",
    kind: "block",
    reason: "the header says the strings stay one word, which FLO-560 makes false",
  },
  {
    id: "scripts-check-class-names-ts-13",
    file: "scripts/check-class-names.ts",
    old: "//     button and a textfield. It reports 128 comparisons, which is 128 for",
    new: "//     button and a text field. It reports 128 comparisons, which is 128 for",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-consumer-ts-91",
    file: "scripts/check-consumer.ts",
    old: "  // textfield 9,600 to 9,700 with no headroom left: next c7858870 measures 9,604 locally",
    new: "  // text field 9,600 to 9,700 with no headroom left: next c7858870 measures 9,604 locally",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-consumer-ts-93",
    file: "scripts/check-consumer.ts",
    old: "  // textfield 9,000 to 9,600 for FLO-301 (the asterisk, the live error, the trailing button):",
    new: "  // text field 9,000 to 9,600 for FLO-301 (the asterisk, the live error, the trailing button):",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-core-ts-107",
    file: "scripts/check-core.ts",
    old: "  await checkTextfield(page);",
    new: "  await checkTextField(page);",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-core-ts-108",
    file: "scripts/check-core.ts",
    old: "  await checkTextfieldTokens(page);",
    new: "  await checkTextFieldTokens(page);",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-core-ts-109",
    file: "scripts/check-core.ts",
    old: "  await checkTextfieldAnatomy(page);",
    new: "  await checkTextFieldAnatomy(page);",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-core-ts-110",
    file: "scripts/check-core.ts",
    old: "  await checkTextfieldPlaceholder(page);",
    new: "  await checkTextFieldPlaceholder(page);",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-core-ts-111",
    file: "scripts/check-core.ts",
    old: "  await checkTextfieldA11y(page);",
    new: "  await checkTextFieldA11y(page);",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-core-ts-112",
    file: "scripts/check-core.ts",
    old: "  await checkTextfieldLatePlacement(page);",
    new: "  await checkTextFieldLatePlacement(page);",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-core-ts-20",
    file: "scripts/check-core.ts",
    old: "import { checkTextfield, checkTextfieldTokens, checkTextfieldAnatomy, checkTextfieldPlaceholder, checkTextfieldA11y, checkTextfieldLatePlacement } from \"./check-text-field-browser\";",
    new: "import { checkTextField, checkTextFieldTokens, checkTextFieldAnatomy, checkTextFieldPlaceholder, checkTextFieldA11y, checkTextFieldLatePlacement } from \"./check-text-field-browser\";",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-elements-registry-ts-31",
    file: "scripts/check-elements-registry.ts",
    old: "  textfield: { event: \"input\", getter: \"value\", factoryEvent: \"input\", action: `const input = host.shadowRoot.querySelector(\"input\"); input.value = \"Ada\"; input.dispatchEvent(new Event(\"input\", { bubbles: true }))` },",
    new: "  textField: { event: \"input\", getter: \"value\", factoryEvent: \"input\", action: `const input = host.shadowRoot.querySelector(\"input\"); input.value = \"Ada\"; input.dispatchEvent(new Event(\"input\", { bubbles: true }))` },",
    action: "replace",
    kind: "line",
    reason: "the registry case key is camelCase textField",
  },
  {
    id: "scripts-check-elements-ts-1171",
    file: "scripts/check-elements.ts",
    old: "  // ---------------------------------------------------------------- textfield",
    new: "  // ---------------------------------------------------------------- text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1184",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: the label attribute is the accessible name\");",
    new: "    check(\"text field: the label attribute is the accessible name\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1202",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: the value attribute is the default, the value property the live value, set silently\");",
    new: "    check(\"text field: the value attribute is the default, the value property the live value, set silently\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1220",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: typing dispatches one input per keystroke and change on commit, and the form sees the value\");",
    new: "    check(\"text field: typing dispatches one input per keystroke and change on commit, and the form sees the value\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1230",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: a new value attribute moves the value until the field is edited, as natively\");",
    new: "    check(\"text field: a new value attribute moves the value until the field is edited, as natively\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1238",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: form.reset() restores the value attribute\");",
    new: "    check(\"text field: form.reset() restores the value attribute\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1276",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: an autofill floats the label, as a typed value does\");",
    new: "    check(\"text field: an autofill floats the label, as a typed value does\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1301",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: required and type constraints report validity to the form, and type recreates keeping the value\");",
    new: "    check(\"text field: required and type constraints report validity to the form, and type recreates keeping the value\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1312",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: an outer <label for> focuses the input\");",
    new: "    check(\"text field: an outer <label for> focuses the input\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1322",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: select() selects the text\");",
    new: "    check(\"text field: select() selects the text\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1350",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: disabled, readonly and a disabled fieldset reach the inner input\");",
    new: "    check(\"text field: disabled, readonly and a disabled fieldset reach the inner input\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1377",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: the error attribute and setError() show the error state\");",
    new: "    check(\"text field: the error attribute and setError() show the error state\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1405",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: attributes with a setter update in place; label recreates keeping the value\");",
    new: "    check(\"text field: attributes with a setter update in place; label recreates keeping the value\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1417",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: type=multiline renders a textarea with the default value\");",
    new: "    check(\"text field: type=multiline renders a textarea with the default value\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1453",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: renders as the factory does with the global stylesheet, filled and outlined\");",
    new: "    check(\"text field: renders as the factory does with the global stylesheet, filled and outlined\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1532",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: a resting label shows alone, enabled or disabled; the prefix and suffix appear as it floats\");",
    new: "    check(\"text field: a resting label shows alone, enabled or disabled; the prefix and suffix appear as it floats\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1552",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: required toggles the input's required and the label's asterisk\");",
    new: "    check(\"text field: required toggles the input's required and the label's asterisk\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1643",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: outlined leaves a notch for the floated label on a coloured card, in shadow DOM, light DOM and rtl, closed at rest\");",
    new: "    check(\"text field: outlined leaves a notch for the floated label on a coloured card, in shadow DOM, light DOM and rtl, closed at rest\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1661",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: focus opens the notch of an empty outlined field and blur closes it\");",
    new: "    check(\"text field: focus opens the notch of an empty outlined field and blur closes it\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-1677",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: an inline-block host whose width the field fills; focus() and blur() reach the input\");",
    new: "    check(\"text field: an inline-block host whose width the field fills; focus() and blur() reach the input\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-elements-ts-4578",
    file: "scripts/check-elements.ts",
    old: "    check(\"textfield: a recreation keeps the live value and whether it is dirty\");",
    new: "    check(\"text field: a recreation keeps the live value and whether it is dirty\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-package-size-ts-242",
    file: "scripts/check-package-size.ts",
    old: "    // an element carries it: +260 here, +256 button, +267 rail, +260 textfield, +243 form,",
    new: "    // an element carries it: +260 here, +256 button, +267 rail, +260 text field, +243 form,",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-package-size-ts-254",
    file: "scripts/check-package-size.ts",
    old: "    // carries it: +71 here, +79 button, +85 rail, +77 textfield, +87 form,",
    new: "    // carries it: +71 here, +79 button, +85 rail, +77 text field, +87 form,",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-react-ts-195",
    file: "scripts/check-react.ts",
    old: "    // ------------------------------------------------------------- textfield",
    new: "    // ------------------------------------------------------------- text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-react-ts-199",
    file: "scripts/check-react.ts",
    old: "    check(\"textfield: controlled value and onInput\");",
    new: "    check(\"text field: controlled value and onInput\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-solid-ssr-ts-41",
    file: "scripts/check-solid-ssr.ts",
    old: "// Component names as the adapters export them: textfield is TextField (FLO-383)",
    new: "// Component names as the adapters export them: text field is TextField (FLO-383)",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-solid-ts-200",
    file: "scripts/check-solid.ts",
    old: "    // ------------------------------------------------------------- textfield",
    new: "    // ------------------------------------------------------------- text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-solid-ts-204",
    file: "scripts/check-solid.ts",
    old: "    check(\"textfield: controlled value and onInput\");",
    new: "    check(\"text field: controlled value and onInput\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-svelte-ssr-ts-20",
    file: "scripts/check-svelte-ssr.ts",
    old: "// Component names as the adapters export them: textfield is TextField (FLO-383)",
    new: "// Component names as the adapters export them: text field is TextField (FLO-383)",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-svelte-ts-199",
    file: "scripts/check-svelte.ts",
    old: "    // ------------------------------------------------------------- textfield",
    new: "    // ------------------------------------------------------------- text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-svelte-ts-203",
    file: "scripts/check-svelte.ts",
    old: "    check(\"textfield: bind:value\");",
    new: "    check(\"text field: bind:value\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-svelte-ts-78",
    file: "scripts/check-svelte.ts",
    old: "    assert.doesNotMatch(index, /Textfield/, file);",
    new: "    assert.doesNotMatch(index, /Textfield/, file);",
    action: "keep",
    kind: "line",
    reason: "pins that the generated Svelte index has no Textfield spelling",
  },
  {
    id: "scripts-check-tabs-ts-13",
    file: "scripts/check-tabs.ts",
    old: "// `consumer:check` renders a button and a textfield only. This is the",
    new: "// `consumer:check` renders a button and a text field only. This is the",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-text-field-browser-ts-173",
    file: "scripts/check-text-field-browser.ts",
    old: "export async function checkTextfieldAnatomy(page: Page): Promise<void> {",
    new: "export async function checkTextFieldAnatomy(page: Page): Promise<void> {",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-text-field-browser-ts-19",
    file: "scripts/check-text-field-browser.ts",
    old: "export async function checkTextfield(page: Page): Promise<void> {",
    new: "export async function checkTextField(page: Page): Promise<void> {",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-text-field-browser-ts-244",
    file: "scripts/check-text-field-browser.ts",
    old: "export async function checkTextfieldPlaceholder(page: Page): Promise<void> {",
    new: "export async function checkTextFieldPlaceholder(page: Page): Promise<void> {",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-text-field-browser-ts-308",
    file: "scripts/check-text-field-browser.ts",
    old: "export async function checkTextfieldA11y(page: Page): Promise<void> {",
    new: "export async function checkTextFieldA11y(page: Page): Promise<void> {",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-text-field-browser-ts-386",
    file: "scripts/check-text-field-browser.ts",
    old: "export async function checkTextfieldLatePlacement(page: Page): Promise<void> {",
    new: "export async function checkTextFieldLatePlacement(page: Page): Promise<void> {",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-text-field-browser-ts-72",
    file: "scripts/check-text-field-browser.ts",
    old: "export async function checkTextfieldTokens(page: Page): Promise<void> {",
    new: "export async function checkTextFieldTokens(page: Page): Promise<void> {",
    action: "replace",
    kind: "line",
    reason: "checkTextfield becomes checkTextField",
  },
  {
    id: "scripts-check-token-render-ts-92",
    file: "scripts/check-token-render.ts",
    old: "  textfield: { make: `m.createTextField({ label: \"Name\", value: \"Ada\" }).element` },",
    new: "  \"text-field\": { make: `m.createTextField({ label: \"Name\", value: \"Ada\" }).element` },",
    action: "replace",
    kind: "line",
    reason: "the token case key is the spec name, quoted kebab",
  },
  {
    id: "scripts-check-vue-ts-180",
    file: "scripts/check-vue.ts",
    old: "    // ------------------------------------------------------------- textfield",
    new: "    // ------------------------------------------------------------- text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-check-vue-ts-184",
    file: "scripts/check-vue.ts",
    old: "    check(\"textfield: v-model\");",
    new: "    check(\"text field: v-model\");",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-fixtures-ssr-parity-ts-9",
    file: "scripts/fixtures/ssr-parity.ts",
    old: "const generated = /^(?:mtrl-|textfield-|select-|tabs-|tab-|radio-|checkbox-|switch-|menu-|search-|datepicker-|timepicker-|dialog-|card-)/;",
    new: "const generated = /^(?:mtrl-|text-field-|select-|tabs-|tab-|radio-|checkbox-|switch-|menu-|search-|datepicker-|timepicker-|dialog-|card-)/;",
    action: "replace",
    kind: "line",
    reason: "the generated id family follows the component name",
  },
  {
    id: "scripts-size-ts-180",
    file: "scripts/size.ts",
    old: "  textfield: kb(8.9),",
    new: "  \"text-field\": kb(8.9),",
    action: "replace",
    kind: "line",
    reason: "the size scenario key is the quoted name text-field",
  },
  {
    id: "scripts-size-ts-28",
    file: "scripts/size.ts",
    old: " * list, navigation-rail, select and switch, and the packed textfield gzip,",
    new: " * list, navigation-rail, select and switch, and the packed text field gzip,",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "scripts-style-manifest-ts-3",
    file: "scripts/style-manifest.ts",
    old: "  textfield: { source: \"components/text-field\", dependencies: [] },",
    new: "  \"text-field\": { source: \"components/text-field\", dependencies: [] },",
    action: "replace",
    kind: "line",
    reason: "the style manifest key is the spec name, quoted kebab",
  },
  {
    id: "src-components-chips-features-container-ts-20",
    file: "src/components/chips/features/container.ts",
    old: "  // textfield's withDensity (#109).",
    new: "  // text field's withDensity (#109).",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-menu-features-opener-ts-257",
    file: "src/components/menu/features/opener.ts",
    old: "    // Case 2: Component with input that can be focused (like textfield)",
    new: "    // Case 2: Component with input that can be focused (like text field)",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-menu-features-opener-ts-97",
    file: "src/components/menu/features/opener.ts",
    old: "      // Case 3: Component with input property (like textfield)",
    new: "      // Case 3: Component with input property (like text field)",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-radios-radio-ts-20",
    file: "src/components/radios/radio.ts",
    old: "  // this one (see textfield's withDensity, #109).",
    new: "  // this one (see text field's withDensity, #109).",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-search-features-input-ts-74",
    file: "src/components/search/features/input.ts",
    old: "  // textfield's withDensity (#109).",
    new: "  // text field's withDensity (#109).",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-search-features-states-ts-43",
    file: "src/components/search/features/states.ts",
    old: "  // textfield's withDensity (#109).",
    new: "  // text field's withDensity (#109).",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-search-features-structure-ts-42",
    file: "src/components/search/features/structure.ts",
    old: "  // textfield's withDensity (#109).",
    new: "  // text field's withDensity (#109).",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-search-features-suggestions-ts-45",
    file: "src/components/search/features/suggestions.ts",
    old: "  // textfield's withDensity (#109).",
    new: "  // text field's withDensity (#109).",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-api-ts-113",
    file: "src/components/select/api.ts",
    old: "      // Delegate to the textfield's setError method",
    new: "      // Delegate to the text field's setError method",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-api-ts-121",
    file: "src/components/select/api.ts",
    old: "      // Clear error state on textfield",
    new: "      // Clear error state on text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-api-ts-16",
    file: "src/components/select/api.ts",
    old: "    // withMenu warns and returns early without a textfield, so a select that",
    new: "    // withMenu warns and returns early without a text field, so a select that",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-api-ts-65",
    file: "src/components/select/api.ts",
    old: "      // Delegate to the textfield's setDensity method",
    new: "      // Delegate to the text field's setDensity method",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-api-ts-73",
    file: "src/components/select/api.ts",
    old: "      // Delegate to the textfield's getDensity method",
    new: "      // Delegate to the text field's getDensity method",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "line-select-class-comment",
    file: "src/components/select/constants.ts",
    old: "  /** The text field (FLO-383: the key is two words; the class value is unchanged) */",
    new: "  /** The text field (FLO-383: the key is two words; the value is select__text-field) */",
    action: "replace",
    kind: "line",
    reason: "the class value changes, so this comment would be false",
  },
  {
    id: "src-components-select-features-ts-12",
    file: "src/components/select/features.ts",
    old: " * Creates a textfield for the select component",
    new: " * Creates a text field for the select component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-features-ts-14",
    file: "src/components/select/features.ts",
    old: " * @returns Function that enhances a component with textfield functionality",
    new: " * @returns Function that enhances a component with text field functionality",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-features-ts-32",
    file: "src/components/select/features.ts",
    old: "    // Create dropdown icon for the textfield",
    new: "    // Create dropdown icon for the text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-features-ts-36",
    file: "src/components/select/features.ts",
    old: "    // Create textfield component",
    new: "    // Create text field component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-features-ts-390",
    file: "src/components/select/features.ts",
    old: "  // Without a textfield the component comes back without menu and select",
    new: "  // Without a text field the component comes back without menu and select",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-features-ts-446",
    file: "src/components/select/features.ts",
    old: "      // Update textfield",
    new: "      // Update text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-features-ts-487",
    file: "src/components/select/features.ts",
    old: "    // Add keyboard event listener for textfield (menu-button selects only)",
    new: "    // Add keyboard event listener for text field (menu-button selects only)",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-features-ts-507",
    file: "src/components/select/features.ts",
    old: "    // Update textfield styling when menu opens/closes",
    new: "    // Update text field styling when menu opens/closes",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-features-ts-524",
    file: "src/components/select/features.ts",
    old: "      // Add focused class to the textfield",
    new: "      // Add focused class to the text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-index-ts-7",
    file: "src/components/select/index.ts",
    old: " * combining a textfield and menu for a complete selection interface.",
    new: " * combining a text field and menu for a complete selection interface.",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-select-ts-15",
    file: "src/components/select/select.ts",
    old: " * combining a textfield and menu to provide a user-friendly selection interface.",
    new: " * combining a text field and menu to provide a user-friendly selection interface.",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-types-ts-145",
    file: "src/components/select/types.ts",
    old: "   * Menu placement relative to the textfield",
    new: "   * Menu placement relative to the text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-select-types-ts-195",
    file: "src/components/select/types.ts",
    old: "   * The textfield component",
    new: "   * The text field component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-slider-features-range-ts-22",
    file: "src/components/slider/features/range.ts",
    old: "  // fixed in textfield's withDensity (#109).",
    new: "  // fixed in text field's withDensity (#109).",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-slider-features-states-ts-28",
    file: "src/components/slider/features/states.ts",
    old: "  // textfield's withDensity (#109).",
    new: "  // text field's withDensity (#109).",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-slider-features-tracks-ts-140",
    file: "src/components/slider/features/tracks.ts",
    old: "  // textfield's withDensity (#109).",
    new: "  // text field's withDensity (#109).",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-api-ts-31",
    file: "src/components/text-field/api.ts",
    old: " * Enhances textfield component with API methods",
    new: " * Enhances text field component with API methods",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-constants-ts-108",
    file: "src/components/text-field/constants.ts",
    old: " * CSS class names used by the textfield component",
    new: " * CSS class names used by the text field component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-constants-ts-59",
    file: "src/components/text-field/constants.ts",
    old: "  /** Fired when textfield receives focus */",
    new: "  /** Fired when text field receives focus */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-constants-ts-61",
    file: "src/components/text-field/constants.ts",
    old: "  /** Fired when textfield loses focus */",
    new: "  /** Fired when text field loses focus */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-constants-ts-85",
    file: "src/components/text-field/constants.ts",
    old: " * Default textfield configuration values",
    new: " * Default text field configuration values",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-features-density-ts-26",
    file: "src/components/text-field/features/density.ts",
    old: " * Adds density support to textfield component",
    new: " * Adds density support to text field component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-features-leading-icon-ts-75",
    file: "src/components/text-field/features/leading-icon.ts",
    old: " * Adds leading icon to a textfield component",
    new: " * Adds leading icon to a text field component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-features-placement-ts-56",
    file: "src/components/text-field/features/placement.ts",
    old: "   * Updates positions of all elements in the textfield",
    new: "   * Updates positions of all elements in the text field",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-features-placement-ts-65",
    file: "src/components/text-field/features/placement.ts",
    old: " * Handles dynamic positioning of textfield elements (label, prefix, suffix)",
    new: " * Handles dynamic positioning of text field elements (label, prefix, suffix)",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-features-prefix-text-ts-73",
    file: "src/components/text-field/features/prefix-text.ts",
    old: " * Adds prefix text to a textfield component",
    new: " * Adds prefix text to a text field component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-features-suffix-text-ts-73",
    file: "src/components/text-field/features/suffix-text.ts",
    old: " * Adds suffix text to a textfield component",
    new: " * Adds suffix text to a text field component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-features-supporting-text-ts-73",
    file: "src/components/text-field/features/supporting-text.ts",
    old: " * Adds supporting text to a textfield component",
    new: " * Adds supporting text to a text field component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-features-trailing-icon-ts-101",
    file: "src/components/text-field/features/trailing-icon.ts",
    old: " * Adds trailing icon to a textfield component",
    new: " * Adds trailing icon to a text field component",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-text-field-ts-104",
    file: "src/components/text-field/text-field.ts",
    old: "      `Failed to create textfield: ${",
    new: "      `Failed to create text field: ${",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-text-field-ts-33",
    file: "src/components/text-field/text-field.ts",
    old: " * This implementation follows Material Design 3 guidelines for accessible, customizable textfields.",
    new: " * This implementation follows Material Design 3 guidelines for accessible, customizable text fields.",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-text-field-ts-36",
    file: "src/components/text-field/text-field.ts",
    old: " * @returns {TextFieldComponent} A fully configured textfield component instance",
    new: " * @returns {TextFieldComponent} A fully configured text field component instance",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-text-field-ts-37",
    file: "src/components/text-field/text-field.ts",
    old: " * @throws {Error} Throws an error if textfield creation fails",
    new: " * @throws {Error} Throws an error if text field creation fails",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-text-field-ts-41",
    file: "src/components/text-field/text-field.ts",
    old: " * const textfield = createTextField({",
    new: " * const textField = createTextField({",
    action: "replace",
    kind: "line",
    reason: "the example binding is textField",
  },
  {
    id: "src-components-text-field-text-field-ts-46",
    file: "src/components/text-field/text-field.ts",
    old: " * document.querySelector('.form').appendChild(textfield.element);",
    new: " * document.querySelector('.form').appendChild(textField.element);",
    action: "replace",
    kind: "line",
    reason: "the example binding is textField",
  },
  {
    id: "src-components-text-field-text-field-ts-66",
    file: "src/components/text-field/text-field.ts",
    old: "    // Build textfield through functional composition",
    new: "    // Build text field through functional composition",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-text-field-ts-68",
    file: "src/components/text-field/text-field.ts",
    old: "    const textfield = pipe(",
    new: "    const textField = pipe(",
    action: "replace",
    kind: "line",
    reason: "the composed binding is textField",
  },
  {
    id: "src-components-text-field-text-field-ts-95",
    file: "src/components/text-field/text-field.ts",
    old: "    if (baseConfig.onTrailingClick) textfield.on(\"trailing\", baseConfig.onTrailingClick);",
    new: "    if (baseConfig.onTrailingClick) textField.on(\"trailing\", baseConfig.onTrailingClick);",
    action: "replace",
    kind: "line",
    reason: "the composed binding is textField",
  },
  {
    id: "src-components-text-field-text-field-ts-97",
    file: "src/components/text-field/text-field.ts",
    old: "    return textfield;",
    new: "    return textField;",
    action: "replace",
    kind: "line",
    reason: "the composed binding is textField",
  },
  {
    id: "src-components-text-field-types-ts-102",
    file: "src/components/text-field/types.ts",
    old: "  /** Whether textfield is readonly */",
    new: "  /** Whether text field is readonly */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-179",
    file: "src/components/text-field/types.ts",
    old: "  /** The root element of the textfield */",
    new: "  /** The root element of the text field */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-191",
    file: "src/components/text-field/types.ts",
    old: "  /** Gets the textfield's value */",
    new: "  /** Gets the text field's value */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-194",
    file: "src/components/text-field/types.ts",
    old: "  /** Sets the textfield's value */",
    new: "  /** Sets the text field's value */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-206",
    file: "src/components/text-field/types.ts",
    old: "  /** Sets the textfield's variant (filled or outlined) */",
    new: "  /** Sets the text field's variant (filled or outlined) */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-209",
    file: "src/components/text-field/types.ts",
    old: "  /** Gets the textfield's current variant */",
    new: "  /** Gets the text field's current variant */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-212",
    file: "src/components/text-field/types.ts",
    old: "  /** Sets the textfield's label text */",
    new: "  /** Sets the text field's label text */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-215",
    file: "src/components/text-field/types.ts",
    old: "  /** Gets the textfield's label text */",
    new: "  /** Gets the text field's label text */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-276",
    file: "src/components/text-field/types.ts",
    old: "  /** Sets the error state of the textfield */",
    new: "  /** Sets the error state of the text field */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-282",
    file: "src/components/text-field/types.ts",
    old: "  /** Sets the density of the textfield */",
    new: "  /** Sets the density of the text field */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-294",
    file: "src/components/text-field/types.ts",
    old: "  /** Enables the textfield */",
    new: "  /** Enables the text field */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-297",
    file: "src/components/text-field/types.ts",
    old: "  /** Disables the textfield */",
    new: "  /** Disables the text field */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-303",
    file: "src/components/text-field/types.ts",
    old: "  /** Destroys the textfield component and cleans up resources */",
    new: "  /** Destroys the text field component and cleans up resources */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-components-text-field-types-ts-381",
    file: "src/components/text-field/types.ts",
    old: "    textfield?: Partial<TextFieldConfig>;",
    new: "    \"text-field\"?: Partial<TextFieldConfig>;",
    action: "replace",
    kind: "line",
    reason: "the defaults map key is quoted kebab, as navigation-rail is",
  },
  {
    id: "src-components-text-field-types-ts-99",
    file: "src/components/text-field/types.ts",
    old: "  /** Whether textfield is disabled */",
    new: "  /** Whether text field is disabled */",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-core-compose-features-textlabel-ts-81",
    file: "src/core/compose/features/textlabel.ts",
    old: "    // textfield. FLO-120.",
    new: "    // text field. FLO-120.",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-core-config-global-ts-70",
    file: "src/core/config/global.ts",
    old: " *   textfield: { variant: 'outlined' }",
    new: " *   \"text-field\": { variant: 'outlined' }",
    action: "replace",
    kind: "line",
    reason: "the defaults example key is quoted kebab, as navigation-rail is",
  },
  {
    id: "src-elements-index-ts-161",
    file: "src/elements/index.ts",
    old: "  textfield: textFieldElement,",
    new: "  textField: textFieldElement,",
    action: "replace",
    kind: "line",
    reason: "the registry key is camelCase textField",
  },
  {
    id: "src-styles-abstract-variables-scss-462",
    file: "src/styles/abstract/_variables.scss",
    old: "/// A text field measurement: `v.text-field('height')`. 0.10's `$textfield` and",
    new: "/// A text field measurement: `v.text-field('height')`. 0.10's `$textfield` and",
    action: "keep",
    kind: "line",
    reason: "names the removed 0.10 Sass spellings $textfield and textfield()",
  },
  {
    id: "src-styles-abstract-variables-scss-463",
    file: "src/styles/abstract/_variables.scss",
    old: "/// `textfield()` are removed in material 3.0.0 (FLO-383).",
    new: "/// `textfield()` are removed in material 3.0.0 (FLO-383).",
    action: "keep",
    kind: "line",
    reason: "names the removed 0.10 Sass spellings $textfield and textfield()",
  },
  {
    id: "src-styles-components-select-scss-11",
    file: "src/styles/components/_select.scss",
    old: "    // Base styles - building on textfield base",
    new: "    // Base styles - building on text field base",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-styles-components-select-scss-30",
    file: "src/styles/components/_select.scss",
    old: "    // Ensure the textfield input works with our select",
    new: "    // Ensure the text field input works with our select",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-styles-components-select-scss-75",
    file: "src/styles/components/_select.scss",
    old: "                top: 28px; // Match the filled textfield's icon positioning",
    new: "                top: 28px; // Match the filled text field's icon positioning",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "src-styles-components-timepicker-scss-155",
    file: "src/styles/components/_timepicker.scss",
    old: "      -moz-appearance: textfield;",
    new: "      -moz-appearance: textfield;",
    action: "keep",
    kind: "line",
    reason: "CSS keyword -moz-appearance: textfield",
  },
  {
    id: "src-styles-main-scss-31",
    file: "src/styles/main.scss",
    old: "@use \"./components/text-field\" as textfield;",
    new: "@use \"./components/text-field\" as text-field;",
    action: "replace",
    kind: "line",
    reason: "the Sass namespace is text-field, and nothing references it",
  },
  {
    id: "test-browser-fixture-ts-30",
    file: "test/browser/fixture.ts",
    old: "  textfield() {",
    new: "  \"text-field\"() {",
    action: "replace",
    kind: "line",
    reason: "the browser fixture case is the component name text-field",
  },
  {
    id: "test-canonical-text-field-test-ts-15",
    file: "test/canonical-text-field.test.ts",
    old: "  \"src/index.ts\": [[\"createTextfield\", \"createTextField\"], [\"TextfieldConfig\", \"TextFieldConfig\"], [\"TextfieldComponent\", \"TextFieldComponent\"],",
    new: "  \"src/index.ts\": [[\"createTextfield\", \"createTextField\"], [\"TextfieldConfig\", \"TextFieldConfig\"], [\"TextfieldComponent\", \"TextFieldComponent\"],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-17",
    file: "test/canonical-text-field.test.ts",
    old: "  \"src/components/text-field/index.ts\": [[\"TextfieldConfig\", \"TextFieldConfig\"], [\"TextfieldComponent\", \"TextFieldComponent\"],",
    new: "  \"src/components/text-field/index.ts\": [[\"TextfieldConfig\", \"TextFieldConfig\"], [\"TextfieldComponent\", \"TextFieldComponent\"],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-18",
    file: "test/canonical-text-field.test.ts",
    old: "    [\"TextfieldDensity\", \"TextFieldDensity\"], [\"TextfieldEvents\", \"TextFieldEvents\"], [\"TextfieldValuePayload\", \"TextFieldValuePayload\"],",
    new: "    [\"TextfieldDensity\", \"TextFieldDensity\"], [\"TextfieldEvents\", \"TextFieldEvents\"], [\"TextfieldValuePayload\", \"TextFieldValuePayload\"],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-19",
    file: "test/canonical-text-field.test.ts",
    old: "    [\"TextfieldFocusPayload\", \"TextFieldFocusPayload\"], [\"TextfieldTrailingPayload\", \"TextFieldTrailingPayload\"]],",
    new: "    [\"TextfieldFocusPayload\", \"TextFieldFocusPayload\"], [\"TextfieldTrailingPayload\", \"TextFieldTrailingPayload\"]],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-20",
    file: "test/canonical-text-field.test.ts",
    old: "  \"src/components/text-field/constants.ts\": CONSTANTS.map((c) => [`TEXTFIELD_${c}`, `TEXT_FIELD_${c}`]),",
    new: "  \"src/components/text-field/constants.ts\": CONSTANTS.map((c) => [`TEXTFIELD_${c}`, `TEXT_FIELD_${c}`]),",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-24",
    file: "test/canonical-text-field.test.ts",
    old: "  \"src/elements/index.ts\": [[\"textfieldElement\", \"textFieldElement\"], [\"defineTextfield\", \"defineTextField\"], [\"TextfieldSpec\", \"TextFieldSpec\"],",
    new: "  \"src/elements/index.ts\": [[\"textfieldElement\", \"textFieldElement\"], [\"defineTextfield\", \"defineTextField\"], [\"TextfieldSpec\", \"TextFieldSpec\"],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-25",
    file: "test/canonical-text-field.test.ts",
    old: "    [\"TextfieldElement\", \"TextFieldElement\"], [\"TextfieldElementComponent\", \"TextFieldElementComponent\"]],",
    new: "    [\"TextfieldElement\", \"TextFieldElement\"], [\"TextfieldElementComponent\", \"TextFieldElementComponent\"]],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-26",
    file: "test/canonical-text-field.test.ts",
    old: "  \"src/react/index.ts\": [[\"Textfield\", \"TextField\"]],",
    new: "  \"src/react/index.ts\": [[\"Textfield\", \"TextField\"]],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-27",
    file: "test/canonical-text-field.test.ts",
    old: "  \"src/solid/index.ts\": [[\"Textfield\", \"TextField\"]],",
    new: "  \"src/solid/index.ts\": [[\"Textfield\", \"TextField\"]],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-28",
    file: "test/canonical-text-field.test.ts",
    old: "  \"src/vue/index.ts\": [[\"MTextfield\", \"MTextField\"]],",
    new: "  \"src/vue/index.ts\": [[\"MTextfield\", \"MTextField\"]],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-canonical-text-field-test-ts-47",
    file: "test/canonical-text-field.test.ts",
    old: "    for (const name of names) if (/Textfield|textfield[A-Z]|TEXTFIELD/.test(name)) problems.push(`${file} exports ${name}`);",
    new: "    for (const name of names) if (/Textfield|textfield[A-Z]|TEXTFIELD/.test(name)) problems.push(`${file} exports ${name}`);",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-component-exports-test-ts-52",
    file: "test/component-exports.test.ts",
    old: "    for (const [component, old, to] of [[\"text-field\", \"TextfieldConfig\", \"TextFieldConfig\"], [\"text-field\", \"TextfieldComponent\", \"TextFieldComponent\"],",
    new: "    for (const [component, old, to] of [[\"text-field\", \"TextfieldConfig\", \"TextFieldConfig\"], [\"text-field\", \"TextfieldComponent\", \"TextFieldComponent\"],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-component-exports-test-ts-54",
    file: "test/component-exports.test.ts",
    old: "      [\"text-field/constants\", \"TEXTFIELD_CLASSES\", \"TEXT_FIELD_CLASSES\"]]) {",
    new: "      [\"text-field/constants\", \"TEXTFIELD_CLASSES\", \"TEXT_FIELD_CLASSES\"]]) {",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-components-bem-runtime-fixture-ts-46",
    file: "test/components/bem-runtime.fixture.ts",
    old: "test(\"textfield constants select live slots and their error state\", () => {",
    new: "test(\"text field constants select live slots and their error state\", () => {",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "test-components-bem-runtime-fixture-ts-56",
    file: "test/components/bem-runtime.fixture.ts",
    old: "test(\"textfield icon setters add and remove BEM input modifiers\", () => {",
    new: "test(\"text field icon setters add and remove BEM input modifiers\", () => {",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "test-components-select-select-test-ts-86",
    file: "test/components/select/select.test.ts",
    old: "test('select.textField is the text field; 3.0.0 keeps no textfield alias, which reads undefined (FLO-383)', () => {",
    new: "test('select.textField is the text field; 3.0.0 keeps no textfield alias, which reads undefined (FLO-383)', () => {",
    action: "keep",
    kind: "line",
    reason: "pins that select.textfield reads undefined",
  },
  {
    id: "test-components-select-select-test-ts-89",
    file: "test/components/select/select.test.ts",
    old: "  expect((select as unknown as Record<string, unknown>).textfield).toBeUndefined();",
    new: "  expect((select as unknown as Record<string, unknown>).textfield).toBeUndefined();",
    action: "keep",
    kind: "line",
    reason: "pins that select.textfield reads undefined",
  },
  {
    id: "test-components-select-select-test-ts-90",
    file: "test/components/select/select.test.ts",
    old: "  expect('textfield' in select).toBe(false);",
    new: "  expect('textfield' in select).toBe(false);",
    action: "keep",
    kind: "line",
    reason: "pins that select.textfield reads undefined",
  },
  {
    id: "test-components-text-field-lifecycle-test-ts-5",
    file: "test/components/text-field/lifecycle.test.ts",
    old: "test(\"real textfield lifecycle regressions\", async () => {",
    new: "test(\"real text field lifecycle regressions\", async () => {",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "test-components-text-field-text-field-test-ts-3",
    file: "test/components/text-field/text-field.test.ts",
    old: "// The real textfield in a JSDOM document: its labelled input and attributes,",
    new: "// The real text field in a JSDOM document: its labelled input and attributes,",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "test-components-text-field-text-field-test-ts-338",
    file: "test/components/text-field/text-field.test.ts",
    old: "describe('textfield outline notch', () => {",
    new: "describe('text field outline notch', () => {",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "test-components-text-field-text-field-test-ts-437",
    file: "test/components/text-field/text-field.test.ts",
    old: "  describe(`textfield ${inputType} event contract`, () => {",
    new: "  describe(`text field ${inputType} event contract`, () => {",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "test-root-exports-test-ts-44",
    file: "test/root-exports.test.ts",
    old: "    const renames = [[\"createTextfield\", \"createTextField\"], [\"TextfieldConfig\", \"TextFieldConfig\"],",
    new: "    const renames = [[\"createTextfield\", \"createTextField\"], [\"TextfieldConfig\", \"TextFieldConfig\"],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-root-exports-test-ts-45",
    file: "test/root-exports.test.ts",
    old: "      [\"TextfieldComponent\", \"TextFieldComponent\"], [\"CardSchema\", \"CardConfig\"],",
    new: "      [\"TextfieldComponent\", \"TextFieldComponent\"], [\"CardSchema\", \"CardConfig\"],",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-ssr-scope-fixture-ts-320",
    file: "test/ssr/scope.fixture.ts",
    old: "test(\"textfield and select disposal reset the shared batch for a subsequent normal DOM lifecycle\", async () => {",
    new: "test(\"text field and select disposal reset the shared batch for a subsequent normal DOM lifecycle\", async () => {",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
  {
    id: "test-ssr-scope-fixture-ts-321",
    file: "test/ssr/scope.fixture.ts",
    old: "  for (const definition of [elements.textfield, elements.select, elements.textfield, elements.select]) {",
    new: "  for (const definition of [elements.textField, elements.select, elements.textField, elements.select]) {",
    action: "replace",
    kind: "line",
    reason: "the registry key is camelCase textField",
  },
  {
    id: "test-styles-bem-element-names-test-ts-41",
    file: "test/styles/bem-element-names.test.ts",
    old: "  textfield: [",
    new: "  \"text-field\": [",
    action: "replace",
    kind: "line",
    reason: "the element-name map key is quoted kebab",
  },
  {
    id: "test-styles-text-field-sass-test-ts-16",
    file: "test/styles/text-field-sass.test.ts",
    old: "test(\"the 0.10 names $textfield and textfield() are gone\", () => {",
    new: "test(\"the 0.10 names $textfield and textfield() are gone\", () => {",
    action: "keep",
    kind: "line",
    reason: "pins that $textfield and textfield() are gone",
  },
  {
    id: "test-styles-text-field-sass-test-ts-17",
    file: "test/styles/text-field-sass.test.ts",
    old: "  expect(() => compile(`@use 'abstract/variables' as v; a { a: v.textfield('height'); }`)).toThrow(/Undefined function/);",
    new: "  expect(() => compile(`@use 'abstract/variables' as v; a { a: v.textfield('height'); }`)).toThrow(/Undefined function/);",
    action: "keep",
    kind: "line",
    reason: "pins that $textfield and textfield() are gone",
  },
  {
    id: "test-styles-text-field-sass-test-ts-18",
    file: "test/styles/text-field-sass.test.ts",
    old: "  expect(() => compile(`@use 'abstract/variables' as v with ($textfield: ('height': 40px)); a { a: 1; }`)).toThrow(/textfield/);",
    new: "  expect(() => compile(`@use 'abstract/variables' as v with ($textfield: ('height': 40px)); a { a: 1; }`)).toThrow(/textfield/);",
    action: "keep",
    kind: "line",
    reason: "pins that $textfield and textfield() are gone",
  },
  {
    id: "line-canonical-names-comment",
    file: "test/types/canonical-names.fixture.ts",
    old: "// Constant keys are identifiers too: two words; the class value is unchanged",
    new: "// Constant keys are identifiers too: two words, and the class value is select__text-field (FLO-560)",
    action: "replace",
    kind: "line",
    reason: "the pinned class value changes, so this comment would be false",
  },
  {
    id: "test-types-canonical-names-fixture-ts-11",
    file: "test/types/canonical-names.fixture.ts",
    old: "// @ts-expect-error createTextfield is createTextField in 3.0.0",
    new: "// @ts-expect-error createTextfield is createTextField in 3.0.0",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-types-canonical-names-fixture-ts-12",
    file: "test/types/canonical-names.fixture.ts",
    old: "import { createTextfield } from \"../../src\";",
    new: "import { createTextfield } from \"../../src\";",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-types-canonical-names-fixture-ts-13",
    file: "test/types/canonical-names.fixture.ts",
    old: "// @ts-expect-error TextfieldConfig is TextFieldConfig in 3.0.0",
    new: "// @ts-expect-error TextfieldConfig is TextFieldConfig in 3.0.0",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-types-canonical-names-fixture-ts-14",
    file: "test/types/canonical-names.fixture.ts",
    old: "import type { TextfieldConfig } from \"../../src\";",
    new: "import type { TextfieldConfig } from \"../../src\";",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-types-canonical-names-fixture-ts-26",
    file: "test/types/canonical-names.fixture.ts",
    old: "export type Gone = [typeof createTextfield, TextfieldConfig, CardSchema, TopAppBar, BottomAppBar];",
    new: "export type Gone = [typeof createTextfield, TextfieldConfig, CardSchema, TopAppBar, BottomAppBar];",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-types-canonical-names-fixture-ts-31",
    file: "test/types/canonical-names.fixture.ts",
    old: "// @ts-expect-error select.textfield is select.textField in 3.0.0, with no alias",
    new: "// @ts-expect-error select.textfield is select.textField in 3.0.0, with no alias",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-types-canonical-names-fixture-ts-32",
    file: "test/types/canonical-names.fixture.ts",
    old: "export const oldSelectField = select.textfield;",
    new: "export const oldSelectField = select.textfield;",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-types-canonical-names-fixture-ts-44",
    file: "test/types/canonical-names.fixture.ts",
    old: "// @ts-expect-error SELECT_CLASSES.TEXTFIELD is TEXT_FIELD in 3.0.0",
    new: "// @ts-expect-error SELECT_CLASSES.TEXTFIELD is TEXT_FIELD in 3.0.0",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-types-canonical-names-fixture-ts-45",
    file: "test/types/canonical-names.fixture.ts",
    old: "export const oldSelectFieldKey = SELECT_CLASSES.TEXTFIELD;",
    new: "export const oldSelectFieldKey = SELECT_CLASSES.TEXTFIELD;",
    action: "keep",
    kind: "line",
    reason: "pins the removed 0.10 identifier spellings",
  },
  {
    id: "test-types-elements-fixture-ts-51",
    file: "test/types/elements.fixture.ts",
    old: "type TextfieldProps = ElementProps<TextFieldSpec>;",
    new: "type TextFieldProps = ElementProps<TextFieldSpec>;",
    action: "replace",
    kind: "line",
    reason: "TextfieldProps becomes TextFieldProps",
  },
  {
    id: "test-types-elements-fixture-ts-52",
    file: "test/types/elements.fixture.ts",
    old: "assert<Equals<TextfieldProps[\"value\"], string | undefined>>();",
    new: "assert<Equals<TextFieldProps[\"value\"], string | undefined>>();",
    action: "replace",
    kind: "line",
    reason: "TextfieldProps becomes TextFieldProps",
  },
  {
    id: "test-types-elements-fixture-ts-53",
    file: "test/types/elements.fixture.ts",
    old: "assert<Equals<TextfieldProps[\"maxlength\"], number | undefined>>();",
    new: "assert<Equals<TextFieldProps[\"maxlength\"], number | undefined>>();",
    action: "replace",
    kind: "line",
    reason: "TextfieldProps becomes TextFieldProps",
  },
  {
    id: "test-types-react-fixture-ts-41",
    file: "test/types/react.fixture.ts",
    old: "type TextfieldProps = ReactProps<typeof TextField>;",
    new: "type TextFieldProps = ReactProps<typeof TextField>;",
    action: "replace",
    kind: "line",
    reason: "TextfieldProps becomes TextFieldProps",
  },
  {
    id: "test-types-react-fixture-ts-43",
    file: "test/types/react.fixture.ts",
    old: "assert<Equals<TextfieldProps[\"value\"], string | undefined>>();",
    new: "assert<Equals<TextFieldProps[\"value\"], string | undefined>>();",
    action: "replace",
    kind: "line",
    reason: "TextfieldProps becomes TextFieldProps",
  },
  {
    id: "test-types-react-fixture-ts-44",
    file: "test/types/react.fixture.ts",
    old: "assert<Equals<TextfieldProps[\"defaultValue\"], string | undefined>>();",
    new: "assert<Equals<TextFieldProps[\"defaultValue\"], string | undefined>>();",
    action: "replace",
    kind: "line",
    reason: "TextfieldProps becomes TextFieldProps",
  },
  {
    id: "test-types-react-fixture-ts-45",
    file: "test/types/react.fixture.ts",
    old: "assert<Equals<TextfieldProps[\"onInput\"], ((event: CustomEvent<{ value: string }>) => void) | undefined>>();",
    new: "assert<Equals<TextFieldProps[\"onInput\"], ((event: CustomEvent<{ value: string }>) => void) | undefined>>();",
    action: "replace",
    kind: "line",
    reason: "TextfieldProps becomes TextFieldProps",
  },
  {
    id: "test-types-text-field-events-fixture-ts-1",
    file: "test/types/text-field-events.fixture.ts",
    old: "// FLO-114: public textfield event names and the payloads its input feature emits.",
    new: "// FLO-114: public text field event names and the payloads its input feature emits.",
    action: "replace",
    kind: "line",
    reason: "prose is two words, text field",
  },
];
