// src/react/bottom-sheet.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "material/elements/css/bottom-sheet";
import { bottomSheetElement, defineBottomSheet, type BottomSheetSpec, type BottomSheetElement } from "../elements/bottom-sheet";
import { createComponent, type MComponent } from "./create";

export const BottomSheet: MComponent<BottomSheetSpec, BottomSheetElement> = /*#__PURE__*/ createComponent(bottomSheetElement.spec, defineBottomSheet, "BottomSheet");
