// src/react/button-group-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import { buttonGroupItemDeclaration, type ButtonGroupItemAttributes } from "../elements/button-group";
import { createDeclaration, type MDeclaration } from "./create";

export const ButtonGroupItem: MDeclaration<ButtonGroupItemAttributes> = /*#__PURE__*/ createDeclaration(buttonGroupItemDeclaration, "ButtonGroupItem");
