// src/react/carousel.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "material/elements/css/carousel";
import { carouselElement, defineCarousel, type CarouselSpec, type CarouselElement } from "../elements/carousel";
import { createComponent, type MComponent } from "./create";

export const Carousel: MComponent<CarouselSpec, CarouselElement> = /*#__PURE__*/ createComponent(carouselElement.spec, defineCarousel, "Carousel");
