// src/react/chip.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import { chipDeclaration, type ChipAttributes } from "../elements/chips";
import { createDeclaration, type MDeclaration } from "./create";

export const Chip: MDeclaration<ChipAttributes> = /*#__PURE__*/ createDeclaration(chipDeclaration, "Chip");
