// src/react/css.d.ts
// The elements' CSS modules are generated by the build (dist/elements/css) and
// imported for their side effect through the package's own name, so they
// resolve to the same registry as the elements in any bundler.
declare module "mtrl/elements/css/*";
