// src/react/dialog.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "material/elements/css/progress";
import "material/elements/css/button";
import "material/elements/css/divider";
import "material/elements/css/dialog";
import { dialogElement, defineDialog, type DialogSpec, type DialogElement } from "../elements/dialog";
import { createComponent, type MComponent } from "./create";

export const Dialog: MComponent<DialogSpec, DialogElement> = /*#__PURE__*/ createComponent(dialogElement.spec, defineDialog, "Dialog");
