// src/react/divider.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "material/elements/css/divider";
import { dividerElement, defineDivider, type DividerSpec, type DividerElement } from "../elements/divider";
import { createComponent, type MComponent } from "./create";

export const Divider: MComponent<DividerSpec, DividerElement> = /*#__PURE__*/ createComponent(dividerElement.spec, defineDivider, "Divider");
