// src/react/drawer.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "mtrl/elements/css/drawer";
import { drawerElement, defineDrawer, type DrawerSpec, type DrawerElement } from "../elements/drawer";
import { createComponent, type MComponent } from "./create";

export const Drawer: MComponent<DrawerSpec, DrawerElement> = /*#__PURE__*/ createComponent(drawerElement.spec, defineDrawer, "Drawer");
