// src/react/drawer-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import { drawerItemDeclaration, type DrawerItemAttributes } from "../elements/drawer";
import { createDeclaration, type MDeclaration } from "./create";

export const DrawerItem: MDeclaration<DrawerItemAttributes> = /*#__PURE__*/ createDeclaration(drawerItemDeclaration, "DrawerItem");
