// src/react/extended-fab.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "material/elements/css/extended-fab";
import { extendedFabElement, defineExtendedFab, type ExtendedFabSpec, type ExtendedFabElement } from "../elements/extended-fab";
import { createComponent, type MComponent } from "./create";

export const ExtendedFab: MComponent<ExtendedFabSpec, ExtendedFabElement> = /*#__PURE__*/ createComponent(extendedFabElement.spec, defineExtendedFab, "ExtendedFab");
