// src/react/index.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
/**
 * React components for the elements. Each renders its `<m-*>` tag, registers
 * it on first mount and loads its CSS.
 *
 * @module react
 */

import "mtrl/elements/css/progress";
import "mtrl/elements/css/button";
import "mtrl/elements/css/switch";
import "mtrl/elements/css/badge";
import "mtrl/elements/css/tabs";
import "mtrl/elements/css/icon-button";
import "mtrl/elements/css/fab";
import "mtrl/elements/css/extended-fab";
import "mtrl/elements/css/checkbox";
import {
  buttonElement,
  defineButton,
  switchElement,
  defineSwitch,
  tabsElement,
  defineTabs,
  iconButtonElement,
  defineIconButton,
  fabElement,
  defineFab,
  extendedFabElement,
  defineExtendedFab,
  checkboxElement,
  defineCheckbox,
  tabDeclaration,
} from "../elements";
import type {
  ButtonSpec,
  ButtonElement,
  SwitchSpec,
  SwitchElement,
  TabsSpec,
  TabsElement,
  IconButtonSpec,
  IconButtonElement,
  FabSpec,
  FabElement,
  ExtendedFabSpec,
  ExtendedFabElement,
  CheckboxSpec,
  CheckboxElement,
  TabAttributes,
} from "../elements";
import { createComponent, createDeclaration, type MComponent, type MDeclaration } from "./create";

export { configure } from "./create";
export type { ComponentProps, DeclarationProps, EventProps, DefaultProps, FormProps, MComponent, MDeclaration } from "./create";

export const Button: MComponent<ButtonSpec, ButtonElement> = createComponent(buttonElement.spec, defineButton, "Button");
export const Switch: MComponent<SwitchSpec, SwitchElement> = createComponent(switchElement.spec, defineSwitch, "Switch");
export const Tabs: MComponent<TabsSpec, TabsElement> = createComponent(tabsElement.spec, defineTabs, "Tabs");
export const IconButton: MComponent<IconButtonSpec, IconButtonElement> = createComponent(iconButtonElement.spec, defineIconButton, "IconButton");
export const Fab: MComponent<FabSpec, FabElement> = createComponent(fabElement.spec, defineFab, "Fab");
export const ExtendedFab: MComponent<ExtendedFabSpec, ExtendedFabElement> = createComponent(extendedFabElement.spec, defineExtendedFab, "ExtendedFab");
export const Checkbox: MComponent<CheckboxSpec, CheckboxElement> = createComponent(checkboxElement.spec, defineCheckbox, "Checkbox");
export const Tab: MDeclaration<TabAttributes> = createDeclaration(tabDeclaration, "Tab");
