// src/react/jsx.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
/**
 * Types the bare `m-*` tags in React's JSX, for the elements used directly
 * rather than through the components. Types only, opt in once: `import type {} from "mtrl/react/jsx";`
 *
 * @module react/jsx
 */
import type * as React from "react";
import type { ElementEvents, ElementMarkup } from "../elements";
import type { ReactHostAttributes } from "./create";

/**
 * The element's events as React 19 listens to them on a custom element: an
 * `on<event>` prop in lower case gets the element's own event
 * (`onchange={(e) => e.detail.value}`). `onChange` stays React's synthetic
 * event, which has no `detail`; React 18 sets no event props on a custom element.
 */
type Events<S> = {
  [K in keyof ElementEvents<S> & string as `on${Lowercase<K>}`]?: (event: ElementEvents<S>[K]) => void;
};

/** A tag's props: its attributes as markup writes them, its events, and any HTML attribute. */
type Tag<S, E extends HTMLElement> = Omit<
  React.DetailedHTMLProps<ReactHostAttributes<E>, E>,
  keyof ElementMarkup<S> | keyof Events<S>
> &
  ElementMarkup<S> &
  Events<S>;

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace -- JSX is a namespace; this merges into it
  namespace JSX {
    interface IntrinsicElements {
      "m-button": Tag<import("../elements/button").ButtonSpec, import("../elements/button").ButtonElement>;
      "m-switch": Tag<import("../elements/switch").SwitchSpec, import("../elements/switch").SwitchElement>;
      "m-tabs": Tag<import("../elements/tabs").TabsSpec, import("../elements/tabs").TabsElement>;
      "m-progress": Tag<import("../elements/progress").ProgressSpec, import("../elements/progress").ProgressElement>;
      "m-loading-indicator": Tag<import("../elements/loading-indicator").LoadingIndicatorSpec, import("../elements/loading-indicator").LoadingIndicatorElement>;
      "m-badge": Tag<import("../elements/badge").BadgeSpec, import("../elements/badge").BadgeElement>;
      "m-divider": Tag<import("../elements/divider").DividerSpec, import("../elements/divider").DividerElement>;
      "m-icon-button": Tag<import("../elements/icon-button").IconButtonSpec, import("../elements/icon-button").IconButtonElement>;
      "m-fab": Tag<import("../elements/fab").FabSpec, import("../elements/fab").FabElement>;
      "m-extended-fab": Tag<import("../elements/extended-fab").ExtendedFabSpec, import("../elements/extended-fab").ExtendedFabElement>;
      "m-checkbox": Tag<import("../elements/checkbox").CheckboxSpec, import("../elements/checkbox").CheckboxElement>;
      "m-slider": Tag<import("../elements/slider").SliderSpec, import("../elements/slider").SliderElement>;
      "m-textfield": Tag<import("../elements/textfield").TextFieldSpec, import("../elements/textfield").TextFieldElement>;
      "m-radios": Tag<import("../elements/radios").RadiosSpec, import("../elements/radios").RadiosElement>;
      "m-navigation-bar": Tag<import("../elements/navigation-bar").NavigationBarSpec, import("../elements/navigation-bar").NavigationBarElement>;
      "m-navigation-rail": Tag<import("../elements/navigation-rail").NavigationRailSpec, import("../elements/navigation-rail").NavigationRailElement>;
      "m-drawer": Tag<import("../elements/drawer").DrawerSpec, import("../elements/drawer").DrawerElement>;
      "m-top-app-bar": Tag<import("../elements/top-app-bar").TopAppBarSpec, import("../elements/top-app-bar").TopAppBarElement>;
      "m-bottom-app-bar": Tag<import("../elements/bottom-app-bar").BottomAppBarSpec, import("../elements/bottom-app-bar").BottomAppBarElement>;
      "m-button-group": Tag<import("../elements/button-group").ButtonGroupSpec, import("../elements/button-group").ButtonGroupElement>;
      "m-chips": Tag<import("../elements/chips").ChipsSpec, import("../elements/chips").ChipsElement>;
      "m-list": Tag<import("../elements/list").ListSpec, import("../elements/list").ListElement>;
      "m-card": Tag<import("../elements/card").CardSpec, import("../elements/card").CardElement>;
      "m-carousel": Tag<import("../elements/carousel").CarouselSpec, import("../elements/carousel").CarouselElement>;
      "m-menu": Tag<import("../elements/menu").MenuSpec, import("../elements/menu").MenuElement>;
      "m-fab-menu": Tag<import("../elements/fab-menu").FabMenuSpec, import("../elements/fab-menu").FabMenuElement>;
      "m-select": Tag<import("../elements/select").SelectSpec, import("../elements/select").SelectElement>;
      "m-split-button": Tag<import("../elements/split-button").SplitButtonSpec, import("../elements/split-button").SplitButtonElement>;
      "m-tooltip": Tag<import("../elements/tooltip").TooltipSpec, import("../elements/tooltip").TooltipElement>;
      "m-toolbar": Tag<import("../elements/toolbar").ToolbarSpec, import("../elements/toolbar").ToolbarElement>;
      "m-snackbar": Tag<import("../elements/snackbar").SnackbarSpec, import("../elements/snackbar").SnackbarElement>;
      "m-dialog": Tag<import("../elements/dialog").DialogSpec, import("../elements/dialog").DialogElement>;
      "m-bottom-sheet": Tag<import("../elements/bottom-sheet").BottomSheetSpec, import("../elements/bottom-sheet").BottomSheetElement>;
      "m-side-sheet": Tag<import("../elements/side-sheet").SideSheetSpec, import("../elements/side-sheet").SideSheetElement>;
      "m-datepicker": Tag<import("../elements/datepicker").DatepickerSpec, import("../elements/datepicker").DatepickerElement>;
      "m-timepicker": Tag<import("../elements/timepicker").TimepickerSpec, import("../elements/timepicker").TimepickerElement>;
      "m-search": Tag<import("../elements/search").SearchSpec, import("../elements/search").SearchElement>;
      "m-tab": Tag<typeof import("../elements/tabs").tabDeclaration, HTMLElement>;
      "m-radio": Tag<typeof import("../elements/radios").radioDeclaration, HTMLElement>;
      "m-navigation-bar-item": Tag<typeof import("../elements/navigation-bar").navigationBarItemDeclaration, HTMLElement>;
      "m-navigation-rail-item": Tag<typeof import("../elements/navigation-rail").navigationRailItemDeclaration, HTMLElement>;
      "m-drawer-item": Tag<typeof import("../elements/drawer").drawerItemDeclaration, HTMLElement>;
      "m-button-group-item": Tag<typeof import("../elements/button-group").buttonGroupItemDeclaration, HTMLElement>;
      "m-chip": Tag<typeof import("../elements/chips").chipDeclaration, HTMLElement>;
      "m-list-item": Tag<typeof import("../elements/list").listItemDeclaration, HTMLElement>;
      "m-carousel-item": Tag<typeof import("../elements/carousel").carouselItemDeclaration, HTMLElement>;
      "m-menu-item": Tag<typeof import("../elements/menu").menuItemDeclaration, HTMLElement>;
      "m-fab-menu-item": Tag<typeof import("../elements/fab-menu").fabMenuItemDeclaration, HTMLElement>;
      "m-select-option": Tag<typeof import("../elements/select").selectOptionDeclaration, HTMLElement>;
      "m-search-suggestion": Tag<typeof import("../elements/search").searchSuggestionDeclaration, HTMLElement>;
    }
  }
}
