// src/react/menu-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import { menuItemDeclaration, type MenuItemAttributes } from "../elements/menu";
import { createDeclaration, type MDeclaration } from "./create";

export const MenuItem: MDeclaration<MenuItemAttributes> = /*#__PURE__*/ createDeclaration(menuItemDeclaration, "MenuItem");
