// src/react/menu.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "material/elements/css/menu";
import { menuElement, defineMenu, type MenuSpec, type MenuElement } from "../elements/menu";
import { createComponent, type MComponent } from "./create";

export const Menu: MComponent<MenuSpec, MenuElement> = /*#__PURE__*/ createComponent(menuElement.spec, defineMenu, "Menu");
