// src/react/navigation-rail.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "material/elements/css/navigation-rail";
import { navigationRailElement, defineNavigationRail, type NavigationRailSpec, type NavigationRailElement } from "../elements/navigation-rail";
import { createComponent, type MComponent } from "./create";

export const NavigationRail: MComponent<NavigationRailSpec, NavigationRailElement> = /*#__PURE__*/ createComponent(navigationRailElement.spec, defineNavigationRail, "NavigationRail");
