// src/react/navigation-bar-item.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import { navigationBarItemDeclaration, type NavigationBarItemAttributes } from "../elements/navigation-bar";
import { createDeclaration, type MDeclaration } from "./create";

export const NavigationBarItem: MDeclaration<NavigationBarItemAttributes> = /*#__PURE__*/ createDeclaration(navigationBarItemDeclaration, "NavigationBarItem");
