// src/react/radios.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "mtrl/elements/css/radios";
import { radiosElement, defineRadios, type RadiosSpec, type RadiosElement } from "../elements/radios";
import { createComponent, type MComponent } from "./create";

export const Radios: MComponent<RadiosSpec, RadiosElement> = /*#__PURE__*/ createComponent(radiosElement.spec, defineRadios, "Radios");
