// src/react/select.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "material/elements/css/text-field";
import "material/elements/css/menu";
import "material/elements/css/select";
import { selectElement, defineSelect, type SelectSpec, type SelectElement } from "../elements/select";
import { createComponent, type MComponent } from "./create";

export const Select: MComponent<SelectSpec, SelectElement> = /*#__PURE__*/ createComponent(selectElement.spec, defineSelect, "Select");
