// src/react/select-option.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import { selectOptionDeclaration, type SelectOptionAttributes } from "../elements/select";
import { createDeclaration, type MDeclaration } from "./create";

export const SelectOption: MDeclaration<SelectOptionAttributes> = /*#__PURE__*/ createDeclaration(selectOptionDeclaration, "SelectOption");
