// src/react/timepicker.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "material/elements/css/timepicker";
import { timepickerElement, defineTimepicker, type TimepickerSpec, type TimepickerElement } from "../elements/timepicker";
import { createComponent, type MComponent } from "./create";

export const Timepicker: MComponent<TimepickerSpec, TimepickerElement> = /*#__PURE__*/ createComponent(timepickerElement.spec, defineTimepicker, "Timepicker");
