// src/react/tooltip.ts
// Generated by scripts/generate-adapters.ts from src/elements. Do not edit.
"use client";
import "mtrl/elements/css/tooltip";
import { tooltipElement, defineTooltip, type TooltipSpec, type TooltipElement } from "../elements/tooltip";
import { createComponent, type MComponent } from "./create";

export const Tooltip: MComponent<TooltipSpec, TooltipElement> = /*#__PURE__*/ createComponent(tooltipElement.spec, defineTooltip, "Tooltip");
